load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "onboarding_get_progress",
    srcs = ["handler.go"],
    importpath = "wappiz/svc/api/routes/v1/onboarding_get_progress",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/db",
        "//pkg/fault",
        "//svc/api/internal/middleware",
        "@com_github_gin_gonic_gin//:gin",
    ],
)
