load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "tenant_flow_fields_update",
    srcs = ["handler.go"],
    importpath = "wappiz/svc/api/routes/v1/tenant_flow_fields_update",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/codes",
        "//pkg/db",
        "//pkg/fault",
        "//pkg/server",
        "//svc/api/internal/middleware",
        "@com_github_gin_gonic_gin//:gin",
        "@com_github_google_uuid//:uuid",
    ],
)

go_test(
    name = "tenant_flow_fields_update_test",
    srcs = ["handler_test.go"],
    embed = [":tenant_flow_fields_update"],
    deps = [
        "//pkg/db",
        "//pkg/server",
        "//svc/api/internal/middleware",
        "//svc/api/internal/testutil",
        "@com_github_gin_gonic_gin//:gin",
        "@com_github_google_uuid//:uuid",
        "@com_github_stretchr_testify//require",
    ],
)
