// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointments_find_by_customer_id.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findAppointmentsByCustomerID = `-- name: FindAppointmentsByCustomerID :many
SELECT a.id,
       a.starts_at,
       a.ends_at,
       a.status,
       a.price_at_booking,
       r.name AS resource_name,
       s.name AS service_name
FROM appointments a
         JOIN resources r ON r.id = a.resource_id
         JOIN services s ON s.id = a.service_id
WHERE a.tenant_id = $1
  AND a.customer_id = $2
  AND a.status = 'confirmed'
  AND a.starts_at > NOW()
ORDER BY a.starts_at
LIMIT 5
`

type FindAppointmentsByCustomerIDParams struct {
	TenantID   uuid.UUID `db:"tenant_id"`
	CustomerID uuid.UUID `db:"customer_id"`
}

type FindAppointmentsByCustomerIDRow struct {
	ID             uuid.UUID         `db:"id"`
	StartsAt       time.Time         `db:"starts_at"`
	EndsAt         time.Time         `db:"ends_at"`
	Status         AppointmentStatus `db:"status"`
	PriceAtBooking string            `db:"price_at_booking"`
	ResourceName   string            `db:"resource_name"`
	ServiceName    string            `db:"service_name"`
}

// FindAppointmentsByCustomerID
//
//	SELECT a.id,
//	       a.starts_at,
//	       a.ends_at,
//	       a.status,
//	       a.price_at_booking,
//	       r.name AS resource_name,
//	       s.name AS service_name
//	FROM appointments a
//	         JOIN resources r ON r.id = a.resource_id
//	         JOIN services s ON s.id = a.service_id
//	WHERE a.tenant_id = $1
//	  AND a.customer_id = $2
//	  AND a.status = 'confirmed'
//	  AND a.starts_at > NOW()
//	ORDER BY a.starts_at
//	LIMIT 5
func (q *Queries) FindAppointmentsByCustomerID(ctx context.Context, db DBTX, arg FindAppointmentsByCustomerIDParams) ([]FindAppointmentsByCustomerIDRow, error) {
	rows, err := db.QueryContext(ctx, findAppointmentsByCustomerID, arg.TenantID, arg.CustomerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindAppointmentsByCustomerIDRow
	for rows.Next() {
		var i FindAppointmentsByCustomerIDRow
		if err := rows.Scan(
			&i.ID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.PriceAtBooking,
			&i.ResourceName,
			&i.ServiceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
