// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointments_mark_reminder_sent.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const mark24hAppointmentReminderSent = `-- name: Mark24hAppointmentReminderSent :exec
UPDATE appointments
SET reminder_24h_sent_at = COALESCE(reminder_24h_sent_at, $1),
    reminder_1h_sent_at  = COALESCE(reminder_1h_sent_at, $2)
WHERE id = $3
`

type Mark24hAppointmentReminderSentParams struct {
	Reminder24hSentAt sql.NullTime `db:"reminder_24h_sent_at"`
	Reminder1hSentAt  sql.NullTime `db:"reminder_1h_sent_at"`
	ID                uuid.UUID    `db:"id"`
}

// Mark24hAppointmentReminderSent
//
//	UPDATE appointments
//	SET reminder_24h_sent_at = COALESCE(reminder_24h_sent_at, $1),
//	    reminder_1h_sent_at  = COALESCE(reminder_1h_sent_at, $2)
//	WHERE id = $3
func (q *Queries) Mark24hAppointmentReminderSent(ctx context.Context, db DBTX, arg Mark24hAppointmentReminderSentParams) error {
	_, err := db.ExecContext(ctx, mark24hAppointmentReminderSent, arg.Reminder24hSentAt, arg.Reminder1hSentAt, arg.ID)
	return err
}
