// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointment_status_history_find.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const findAppointmentStatusHistory = `-- name: FindAppointmentStatusHistory :many
SELECT h.id,
       h.appointment_id,
       h.from_status,
       h.to_status,
       u.name as changed_by,
       h.changed_by_role,
       h.reason,
       h.created_at
FROM appointment_status_history h
         JOIN appointments a ON a.id = h.appointment_id
         LEFT JOIN users u ON u.id = h.changed_by
WHERE h.appointment_id = $1
  AND a.tenant_id = $2
ORDER BY h.created_at
`

type FindAppointmentStatusHistoryParams struct {
	AppointmentID uuid.UUID `db:"appointment_id"`
	TenantID      uuid.UUID `db:"tenant_id"`
}

type FindAppointmentStatusHistoryRow struct {
	ID            uuid.UUID         `db:"id"`
	AppointmentID uuid.UUID         `db:"appointment_id"`
	FromStatus    AppointmentStatus `db:"from_status"`
	ToStatus      AppointmentStatus `db:"to_status"`
	ChangedBy     sql.NullString    `db:"changed_by"`
	ChangedByRole sql.NullString    `db:"changed_by_role"`
	Reason        sql.NullString    `db:"reason"`
	CreatedAt     time.Time         `db:"created_at"`
}

// FindAppointmentStatusHistory
//
//	SELECT h.id,
//	       h.appointment_id,
//	       h.from_status,
//	       h.to_status,
//	       u.name as changed_by,
//	       h.changed_by_role,
//	       h.reason,
//	       h.created_at
//	FROM appointment_status_history h
//	         JOIN appointments a ON a.id = h.appointment_id
//	         LEFT JOIN users u ON u.id = h.changed_by
//	WHERE h.appointment_id = $1
//	  AND a.tenant_id = $2
//	ORDER BY h.created_at
func (q *Queries) FindAppointmentStatusHistory(ctx context.Context, db DBTX, arg FindAppointmentStatusHistoryParams) ([]FindAppointmentStatusHistoryRow, error) {
	rows, err := db.QueryContext(ctx, findAppointmentStatusHistory, arg.AppointmentID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindAppointmentStatusHistoryRow
	for rows.Next() {
		var i FindAppointmentStatusHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.AppointmentID,
			&i.FromStatus,
			&i.ToStatus,
			&i.ChangedBy,
			&i.ChangedByRole,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
