// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointments_insert.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertAppointment = `-- name: InsertAppointment :exec
INSERT INTO appointments(
    id,
    tenant_id,
    resource_id,
    service_id,
    customer_id,
    starts_at,
    ends_at,
    status,
    price_at_booking
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    'confirmed',
    $8
)
`

type InsertAppointmentParams struct {
	ID             uuid.UUID `db:"id"`
	TenantID       uuid.UUID `db:"tenant_id"`
	ResourceID     uuid.UUID `db:"resource_id"`
	ServiceID      uuid.UUID `db:"service_id"`
	CustomerID     uuid.UUID `db:"customer_id"`
	StartsAt       time.Time `db:"starts_at"`
	EndsAt         time.Time `db:"ends_at"`
	PriceAtBooking string    `db:"price_at_booking"`
}

// InsertAppointment
//
//	INSERT INTO appointments(
//	    id,
//	    tenant_id,
//	    resource_id,
//	    service_id,
//	    customer_id,
//	    starts_at,
//	    ends_at,
//	    status,
//	    price_at_booking
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    $7,
//	    'confirmed',
//	    $8
//	)
func (q *Queries) InsertAppointment(ctx context.Context, db DBTX, arg InsertAppointmentParams) error {
	_, err := db.ExecContext(ctx, insertAppointment,
		arg.ID,
		arg.TenantID,
		arg.ResourceID,
		arg.ServiceID,
		arg.CustomerID,
		arg.StartsAt,
		arg.EndsAt,
		arg.PriceAtBooking,
	)
	return err
}
