// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointments_search.sql

package db

import (
	"context"
	"strings"
	"time"

	"github.com/google/uuid"
)

const searchAppointments = `-- name: SearchAppointments :many
SELECT a.id,
       a.starts_at,
       a.ends_at,
       a.status,
       a.price_at_booking,
       r.name                           AS resource_name,
       s.name                           AS service_name,
       COALESCE(c.name, c.phone_number) AS customer_name
FROM appointments a
         JOIN resources r ON r.id = a.resource_id
         JOIN services s ON s.id = a.service_id
         JOIN customers c ON c.id = a.customer_id
WHERE a.tenant_id = $1
  AND a.starts_at >= $2
  AND a.starts_at < $3
  AND a.resource_id = ANY ($4)
  AND a.service_id = ANY ($5)
  AND a.status = ANY ($6)
ORDER BY a.starts_at
`

type SearchAppointmentsParams struct {
	TenantID    uuid.UUID           `db:"tenant_id"`
	StartsAt    time.Time           `db:"starts_at"`
	StartsAt_2  time.Time           `db:"starts_at_2"`
	ResourceIds []uuid.UUID         `db:"resource_ids"`
	ServiceIds  []uuid.UUID         `db:"service_ids"`
	Status      []AppointmentStatus `db:"status"`
}

type SearchAppointmentsRow struct {
	ID             uuid.UUID         `db:"id"`
	StartsAt       time.Time         `db:"starts_at"`
	EndsAt         time.Time         `db:"ends_at"`
	Status         AppointmentStatus `db:"status"`
	PriceAtBooking string            `db:"price_at_booking"`
	ResourceName   string            `db:"resource_name"`
	ServiceName    string            `db:"service_name"`
	CustomerName   string            `db:"customer_name"`
}

// SearchAppointments
//
//	SELECT a.id,
//	       a.starts_at,
//	       a.ends_at,
//	       a.status,
//	       a.price_at_booking,
//	       r.name                           AS resource_name,
//	       s.name                           AS service_name,
//	       COALESCE(c.name, c.phone_number) AS customer_name
//	FROM appointments a
//	         JOIN resources r ON r.id = a.resource_id
//	         JOIN services s ON s.id = a.service_id
//	         JOIN customers c ON c.id = a.customer_id
//	WHERE a.tenant_id = $1
//	  AND a.starts_at >= $2
//	  AND a.starts_at < $3
//	  AND a.resource_id = ANY ($4)
//	  AND a.service_id = ANY ($5)
//	  AND a.status = ANY ($6)
//	ORDER BY a.starts_at
func (q *Queries) SearchAppointments(ctx context.Context, db DBTX, arg SearchAppointmentsParams) ([]SearchAppointmentsRow, error) {
	query := searchAppointments
	var queryParams []interface{}
	queryParams = append(queryParams, arg.TenantID)
	queryParams = append(queryParams, arg.StartsAt)
	queryParams = append(queryParams, arg.StartsAt_2)
	if len(arg.ResourceIds) > 0 {
		for _, v := range arg.ResourceIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:resource_ids*/?", strings.Repeat(",?", len(arg.ResourceIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:resource_ids*/?", "NULL", 1)
	}
	if len(arg.ServiceIds) > 0 {
		for _, v := range arg.ServiceIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:service_ids*/?", strings.Repeat(",?", len(arg.ServiceIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:service_ids*/?", "NULL", 1)
	}
	if len(arg.Status) > 0 {
		for _, v := range arg.Status {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:status*/?", strings.Repeat(",?", len(arg.Status))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:status*/?", "NULL", 1)
	}
	rows, err := db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAppointmentsRow
	for rows.Next() {
		var i SearchAppointmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.PriceAtBooking,
			&i.ResourceName,
			&i.ServiceName,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
