// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointments_has_customer_overlap.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const hasCustomerOverlap = `-- name: HasCustomerOverlap :one
SELECT EXISTS (
    SELECT 1
    FROM appointments a
    WHERE a.tenant_id = $1
      AND a.customer_id = $2
      AND a.status NOT IN ('cancelled', 'no_show')
  AND a.starts_at < $3
  AND a.ends_at > $4
) AS has_overlap
`

type HasCustomerOverlapParams struct {
	TenantID   uuid.UUID `db:"tenant_id"`
	CustomerID uuid.UUID `db:"customer_id"`
	EndsAt     time.Time `db:"ends_at"`
	StartsAt   time.Time `db:"starts_at"`
}

// HasCustomerOverlap
//
//	SELECT EXISTS (
//	    SELECT 1
//	    FROM appointments a
//	    WHERE a.tenant_id = $1
//	      AND a.customer_id = $2
//	      AND a.status NOT IN ('cancelled', 'no_show')
//	  AND a.starts_at < $3
//	  AND a.ends_at > $4
//	) AS has_overlap
func (q *Queries) HasCustomerOverlap(ctx context.Context, db DBTX, arg HasCustomerOverlapParams) (bool, error) {
	row := db.QueryRowContext(ctx, hasCustomerOverlap,
		arg.TenantID,
		arg.CustomerID,
		arg.EndsAt,
		arg.StartsAt,
	)
	var has_overlap bool
	err := row.Scan(&has_overlap)
	return has_overlap, err
}
