// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointments_find_by_id.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findAppointmentByID = `-- name: FindAppointmentByID :one
SELECT id,
       tenant_id,
       resource_id,
       service_id,
       customer_id,
       starts_at,
       ends_at,
       status,
       price_at_booking
FROM appointments
WHERE id = $1
  AND tenant_id = $2
LIMIT 1
`

type FindAppointmentByIDParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

type FindAppointmentByIDRow struct {
	ID             uuid.UUID         `db:"id"`
	TenantID       uuid.UUID         `db:"tenant_id"`
	ResourceID     uuid.UUID         `db:"resource_id"`
	ServiceID      uuid.UUID         `db:"service_id"`
	CustomerID     uuid.UUID         `db:"customer_id"`
	StartsAt       time.Time         `db:"starts_at"`
	EndsAt         time.Time         `db:"ends_at"`
	Status         AppointmentStatus `db:"status"`
	PriceAtBooking string            `db:"price_at_booking"`
}

// FindAppointmentByID
//
//	SELECT id,
//	       tenant_id,
//	       resource_id,
//	       service_id,
//	       customer_id,
//	       starts_at,
//	       ends_at,
//	       status,
//	       price_at_booking
//	FROM appointments
//	WHERE id = $1
//	  AND tenant_id = $2
//	LIMIT 1
func (q *Queries) FindAppointmentByID(ctx context.Context, db DBTX, arg FindAppointmentByIDParams) (FindAppointmentByIDRow, error) {
	row := db.QueryRowContext(ctx, findAppointmentByID, arg.ID, arg.TenantID)
	var i FindAppointmentByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ResourceID,
		&i.ServiceID,
		&i.CustomerID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.PriceAtBooking,
	)
	return i, err
}
