// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointment_status_history_insert.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const insertAppointmentStatusHistory = `-- name: InsertAppointmentStatusHistory :exec
INSERT INTO appointment_status_history(
    id,
    appointment_id,
    from_status,
    to_status,
    changed_by,
    changed_by_role,
    reason,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    NOW()
)
`

type InsertAppointmentStatusHistoryParams struct {
	ID            uuid.UUID         `db:"id"`
	AppointmentID uuid.UUID         `db:"appointment_id"`
	FromStatus    AppointmentStatus `db:"from_status"`
	ToStatus      AppointmentStatus `db:"to_status"`
	ChangedBy     sql.NullString    `db:"changed_by"`
	ChangedByRole sql.NullString    `db:"changed_by_role"`
	Reason        sql.NullString    `db:"reason"`
}

// InsertAppointmentStatusHistory
//
//	INSERT INTO appointment_status_history(
//	    id,
//	    appointment_id,
//	    from_status,
//	    to_status,
//	    changed_by,
//	    changed_by_role,
//	    reason,
//	    created_at
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    $7,
//	    NOW()
//	)
func (q *Queries) InsertAppointmentStatusHistory(ctx context.Context, db DBTX, arg InsertAppointmentStatusHistoryParams) error {
	_, err := db.ExecContext(ctx, insertAppointmentStatusHistory,
		arg.ID,
		arg.AppointmentID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ChangedBy,
		arg.ChangedByRole,
		arg.Reason,
	)
	return err
}
