// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointments_recently_cancelled.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const findRecentlyCancelledAppointments = `-- name: FindRecentlyCancelledAppointments :many
SELECT id,
       tenant_id,
       customer_id,
       resource_id,
       service_id,
       starts_at,
       ends_at,
       status,
       cancelled_at
FROM appointments
WHERE status = 'cancelled'
  AND cancelled_at IS NOT NULL
  AND cancelled_at >= NOW() - INTERVAL '10 minutes'
`

type FindRecentlyCancelledAppointmentsRow struct {
	ID          uuid.UUID         `db:"id"`
	TenantID    uuid.UUID         `db:"tenant_id"`
	CustomerID  uuid.UUID         `db:"customer_id"`
	ResourceID  uuid.UUID         `db:"resource_id"`
	ServiceID   uuid.UUID         `db:"service_id"`
	StartsAt    time.Time         `db:"starts_at"`
	EndsAt      time.Time         `db:"ends_at"`
	Status      AppointmentStatus `db:"status"`
	CancelledAt sql.NullTime      `db:"cancelled_at"`
}

// FindRecentlyCancelledAppointments
//
//	SELECT id,
//	       tenant_id,
//	       customer_id,
//	       resource_id,
//	       service_id,
//	       starts_at,
//	       ends_at,
//	       status,
//	       cancelled_at
//	FROM appointments
//	WHERE status = 'cancelled'
//	  AND cancelled_at IS NOT NULL
//	  AND cancelled_at >= NOW() - INTERVAL '10 minutes'
func (q *Queries) FindRecentlyCancelledAppointments(ctx context.Context, db DBTX) ([]FindRecentlyCancelledAppointmentsRow, error) {
	rows, err := db.QueryContext(ctx, findRecentlyCancelledAppointments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindRecentlyCancelledAppointmentsRow
	for rows.Next() {
		var i FindRecentlyCancelledAppointmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.ResourceID,
			&i.ServiceID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
