// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointments_find_upcoming.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findUpcomingAppointments = `-- name: FindUpcomingAppointments :many
SELECT id, tenant_id, customer_id, resource_id, service_id, starts_at, ends_at
FROM appointments
WHERE status = 'confirmed'
  AND (
    (reminder_24h_sent_at IS NULL AND starts_at BETWEEN NOW() + INTERVAL '23 hours' AND NOW() + INTERVAL '25 hours')
        OR
    (reminder_1h_sent_at IS NULL AND starts_at BETWEEN NOW() + INTERVAL '50 minutes' AND NOW() + INTERVAL '70 minutes')
    )
`

type FindUpcomingAppointmentsRow struct {
	ID         uuid.UUID `db:"id"`
	TenantID   uuid.UUID `db:"tenant_id"`
	CustomerID uuid.UUID `db:"customer_id"`
	ResourceID uuid.UUID `db:"resource_id"`
	ServiceID  uuid.UUID `db:"service_id"`
	StartsAt   time.Time `db:"starts_at"`
	EndsAt     time.Time `db:"ends_at"`
}

// FindUpcomingAppointments
//
//	SELECT id, tenant_id, customer_id, resource_id, service_id, starts_at, ends_at
//	FROM appointments
//	WHERE status = 'confirmed'
//	  AND (
//	    (reminder_24h_sent_at IS NULL AND starts_at BETWEEN NOW() + INTERVAL '23 hours' AND NOW() + INTERVAL '25 hours')
//	        OR
//	    (reminder_1h_sent_at IS NULL AND starts_at BETWEEN NOW() + INTERVAL '50 minutes' AND NOW() + INTERVAL '70 minutes')
//	    )
func (q *Queries) FindUpcomingAppointments(ctx context.Context, db DBTX) ([]FindUpcomingAppointmentsRow, error) {
	rows, err := db.QueryContext(ctx, findUpcomingAppointments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindUpcomingAppointmentsRow
	for rows.Next() {
		var i FindUpcomingAppointmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.ResourceID,
			&i.ServiceID,
			&i.StartsAt,
			&i.EndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
