// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointments_update.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const updateAppointment = `-- name: UpdateAppointment :exec
UPDATE appointments
SET status        = $1,
    updated_at    = NOW(),
    cancelled_by  = $2,
    cancel_reason = $3,
    completed_at  = $4
WHERE id = $5
`

type UpdateAppointmentParams struct {
	Status       AppointmentStatus `db:"status"`
	CancelledBy  sql.NullString    `db:"cancelled_by"`
	CancelReason sql.NullString    `db:"cancel_reason"`
	CompletedAt  sql.NullTime      `db:"completed_at"`
	ID           uuid.UUID         `db:"id"`
}

// UpdateAppointment
//
//	UPDATE appointments
//	SET status        = $1,
//	    updated_at    = NOW(),
//	    cancelled_by  = $2,
//	    cancel_reason = $3,
//	    completed_at  = $4
//	WHERE id = $5
func (q *Queries) UpdateAppointment(ctx context.Context, db DBTX, arg UpdateAppointmentParams) error {
	_, err := db.ExecContext(ctx, updateAppointment,
		arg.Status,
		arg.CancelledBy,
		arg.CancelReason,
		arg.CompletedAt,
		arg.ID,
	)
	return err
}
