// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointments_find_unattended.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findUnattendedAppointments = `-- name: FindUnattendedAppointments :many
SELECT id,
       tenant_id,
       customer_id,
       resource_id,
       service_id,
       starts_at,
       ends_at,
       status
FROM appointments
WHERE status = 'confirmed'
  AND starts_at <= NOW() - INTERVAL '30 minutes'
`

type FindUnattendedAppointmentsRow struct {
	ID         uuid.UUID         `db:"id"`
	TenantID   uuid.UUID         `db:"tenant_id"`
	CustomerID uuid.UUID         `db:"customer_id"`
	ResourceID uuid.UUID         `db:"resource_id"`
	ServiceID  uuid.UUID         `db:"service_id"`
	StartsAt   time.Time         `db:"starts_at"`
	EndsAt     time.Time         `db:"ends_at"`
	Status     AppointmentStatus `db:"status"`
}

// FindUnattendedAppointments
//
//	SELECT id,
//	       tenant_id,
//	       customer_id,
//	       resource_id,
//	       service_id,
//	       starts_at,
//	       ends_at,
//	       status
//	FROM appointments
//	WHERE status = 'confirmed'
//	  AND starts_at <= NOW() - INTERVAL '30 minutes'
func (q *Queries) FindUnattendedAppointments(ctx context.Context, db DBTX) ([]FindUnattendedAppointmentsRow, error) {
	rows, err := db.QueryContext(ctx, findUnattendedAppointments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindUnattendedAppointmentsRow
	for rows.Next() {
		var i FindUnattendedAppointmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.ResourceID,
			&i.ServiceID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
