// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointment_penalty_events_find_customer_incidents.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findCustomerIncidents = `-- name: FindCustomerIncidents :many
SELECT ape.id,
       ape.event_type,
       ape.occurred_at,
       ape.appointment_id,
       a.starts_at,
       s.name AS service_name,
       r.name AS resource_name
FROM appointment_penalty_events ape
         JOIN appointments a ON a.id = ape.appointment_id
         JOIN services s ON s.id = a.service_id
         JOIN resources r ON r.id = a.resource_id
WHERE ape.customer_id = $1
  AND ape.tenant_id = $2
ORDER BY ape.occurred_at DESC
LIMIT 5
`

type FindCustomerIncidentsParams struct {
	CustomerID uuid.UUID `db:"customer_id"`
	TenantID   uuid.UUID `db:"tenant_id"`
}

type FindCustomerIncidentsRow struct {
	ID            uuid.UUID `db:"id"`
	EventType     string    `db:"event_type"`
	OccurredAt    time.Time `db:"occurred_at"`
	AppointmentID uuid.UUID `db:"appointment_id"`
	StartsAt      time.Time `db:"starts_at"`
	ServiceName   string    `db:"service_name"`
	ResourceName  string    `db:"resource_name"`
}

// FindCustomerIncidents
//
//	SELECT ape.id,
//	       ape.event_type,
//	       ape.occurred_at,
//	       ape.appointment_id,
//	       a.starts_at,
//	       s.name AS service_name,
//	       r.name AS resource_name
//	FROM appointment_penalty_events ape
//	         JOIN appointments a ON a.id = ape.appointment_id
//	         JOIN services s ON s.id = a.service_id
//	         JOIN resources r ON r.id = a.resource_id
//	WHERE ape.customer_id = $1
//	  AND ape.tenant_id = $2
//	ORDER BY ape.occurred_at DESC
//	LIMIT 5
func (q *Queries) FindCustomerIncidents(ctx context.Context, db DBTX, arg FindCustomerIncidentsParams) ([]FindCustomerIncidentsRow, error) {
	rows, err := db.QueryContext(ctx, findCustomerIncidents, arg.CustomerID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindCustomerIncidentsRow
	for rows.Next() {
		var i FindCustomerIncidentsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.OccurredAt,
			&i.AppointmentID,
			&i.StartsAt,
			&i.ServiceName,
			&i.ResourceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
