// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointments_find_resource_occupied_slots.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findResourceOccupiedSlots = `-- name: FindResourceOccupiedSlots :many
SELECT starts_at, ends_at
FROM appointments
WHERE resource_id = $1
  AND starts_at >= $2
  AND ends_at <= $3
  AND status NOT IN ('cancelled', 'no_show')
ORDER BY starts_at
`

type FindResourceOccupiedSlotsParams struct {
	ResourceID uuid.UUID `db:"resource_id"`
	StartsAt   time.Time `db:"starts_at"`
	EndsAt     time.Time `db:"ends_at"`
}

type FindResourceOccupiedSlotsRow struct {
	StartsAt time.Time `db:"starts_at"`
	EndsAt   time.Time `db:"ends_at"`
}

// FindResourceOccupiedSlots
//
//	SELECT starts_at, ends_at
//	FROM appointments
//	WHERE resource_id = $1
//	  AND starts_at >= $2
//	  AND ends_at <= $3
//	  AND status NOT IN ('cancelled', 'no_show')
//	ORDER BY starts_at
func (q *Queries) FindResourceOccupiedSlots(ctx context.Context, db DBTX, arg FindResourceOccupiedSlotsParams) ([]FindResourceOccupiedSlotsRow, error) {
	rows, err := db.QueryContext(ctx, findResourceOccupiedSlots, arg.ResourceID, arg.StartsAt, arg.EndsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindResourceOccupiedSlotsRow
	for rows.Next() {
		var i FindResourceOccupiedSlotsRow
		if err := rows.Scan(&i.StartsAt, &i.EndsAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
