// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversation_sessions_find_active_by_customer.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const findCustomerActiveConversationSession = `-- name: FindCustomerActiveConversationSession :one
SELECT id,
       tenant_id,
       whatsapp_config_id,
       customer_id,
       step,
       data,
       expires_at,
       created_at,
       updated_at
FROM conversation_sessions
WHERE tenant_id = $1
  AND customer_id = $2
  AND expires_at > NOW()
LIMIT 1
`

type FindCustomerActiveConversationSessionParams struct {
	TenantID   uuid.UUID `db:"tenant_id"`
	CustomerID uuid.UUID `db:"customer_id"`
}

type FindCustomerActiveConversationSessionRow struct {
	ID               uuid.UUID       `db:"id"`
	TenantID         uuid.UUID       `db:"tenant_id"`
	WhatsappConfigID uuid.UUID       `db:"whatsapp_config_id"`
	CustomerID       uuid.UUID       `db:"customer_id"`
	Step             string          `db:"step"`
	Data             json.RawMessage `db:"data"`
	ExpiresAt        time.Time       `db:"expires_at"`
	CreatedAt        time.Time       `db:"created_at"`
	UpdatedAt        time.Time       `db:"updated_at"`
}

// FindCustomerActiveConversationSession
//
//	SELECT id,
//	       tenant_id,
//	       whatsapp_config_id,
//	       customer_id,
//	       step,
//	       data,
//	       expires_at,
//	       created_at,
//	       updated_at
//	FROM conversation_sessions
//	WHERE tenant_id = $1
//	  AND customer_id = $2
//	  AND expires_at > NOW()
//	LIMIT 1
func (q *Queries) FindCustomerActiveConversationSession(ctx context.Context, db DBTX, arg FindCustomerActiveConversationSessionParams) (FindCustomerActiveConversationSessionRow, error) {
	row := db.QueryRowContext(ctx, findCustomerActiveConversationSession, arg.TenantID, arg.CustomerID)
	var i FindCustomerActiveConversationSessionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WhatsappConfigID,
		&i.CustomerID,
		&i.Step,
		&i.Data,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
