// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversation_sessions_find_active_by_customer.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const findCustomerActiveConversationSession = `-- name: FindCustomerActiveConversationSession :one
SELECT id,
       tenant_id,
       whatsapp_config_id,
       customer_id,
       step,
       data,
       expires_at,
       created_at,
       updated_at
FROM conversation_sessions
WHERE tenant_id = $1
  AND customer_id = $2
  AND expires_at > NOW()
LIMIT 1
`

type FindCustomerActiveConversationSessionParams struct {
	TenantID   uuid.UUID `db:"tenant_id"`
	CustomerID uuid.UUID `db:"customer_id"`
}

// FindCustomerActiveConversationSession
//
//	SELECT id,
//	       tenant_id,
//	       whatsapp_config_id,
//	       customer_id,
//	       step,
//	       data,
//	       expires_at,
//	       created_at,
//	       updated_at
//	FROM conversation_sessions
//	WHERE tenant_id = $1
//	  AND customer_id = $2
//	  AND expires_at > NOW()
//	LIMIT 1
func (q *Queries) FindCustomerActiveConversationSession(ctx context.Context, db DBTX, arg FindCustomerActiveConversationSessionParams) (ConversationSession, error) {
	row := db.QueryRowContext(ctx, findCustomerActiveConversationSession, arg.TenantID, arg.CustomerID)
	var i ConversationSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WhatsappConfigID,
		&i.CustomerID,
		&i.Step,
		&i.Data,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
