// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversation_sessions_update.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const updateConversationSession = `-- name: UpdateConversationSession :exec
UPDATE conversation_sessions
SET step       = $1,
    data       = $2,
    expires_at = $3,
    updated_at = NOW()
WHERE id = $4
`

type UpdateConversationSessionParams struct {
	Step      string          `db:"step"`
	Data      json.RawMessage `db:"data"`
	ExpiresAt time.Time       `db:"expires_at"`
	ID        uuid.UUID       `db:"id"`
}

// UpdateConversationSession
//
//	UPDATE conversation_sessions
//	SET step       = $1,
//	    data       = $2,
//	    expires_at = $3,
//	    updated_at = NOW()
//	WHERE id = $4
func (q *Queries) UpdateConversationSession(ctx context.Context, db DBTX, arg UpdateConversationSessionParams) error {
	_, err := db.ExecContext(ctx, updateConversationSession,
		arg.Step,
		arg.Data,
		arg.ExpiresAt,
		arg.ID,
	)
	return err
}
