// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversation_sessions_delete_expired.sql

package db

import (
	"context"
)

const deleteExpiredConversationSessions = `-- name: DeleteExpiredConversationSessions :exec
DELETE
FROM conversation_sessions
WHERE expires_at < NOW()
`

// DeleteExpiredConversationSessions
//
//	DELETE
//	FROM conversation_sessions
//	WHERE expires_at < NOW()
func (q *Queries) DeleteExpiredConversationSessions(ctx context.Context, db DBTX) error {
	_, err := db.ExecContext(ctx, deleteExpiredConversationSessions)
	return err
}
