// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversation_sessions_delete.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteConversationSession = `-- name: DeleteConversationSession :exec
DELETE
FROM conversation_sessions
WHERE id = $1
`

// DeleteConversationSession
//
//	DELETE
//	FROM conversation_sessions
//	WHERE id = $1
func (q *Queries) DeleteConversationSession(ctx context.Context, db DBTX, id uuid.UUID) error {
	_, err := db.ExecContext(ctx, deleteConversationSession, id)
	return err
}
