// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers_unblock.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const unblockCustomer = `-- name: UnblockCustomer :exec
UPDATE customers
SET is_blocked = false
WHERE id = $1
  AND tenant_id = $2
`

type UnblockCustomerParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

// UnblockCustomer
//
//	UPDATE customers
//	SET is_blocked = false
//	WHERE id = $1
//	  AND tenant_id = $2
func (q *Queries) UnblockCustomer(ctx context.Context, db DBTX, arg UnblockCustomerParams) error {
	_, err := db.ExecContext(ctx, unblockCustomer, arg.ID, arg.TenantID)
	return err
}
