// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers_find_by_tenant.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const findCustomersByTenant = `-- name: FindCustomersByTenant :many
SELECT id, tenant_id, phone_number, name, is_blocked, created_at
FROM customers
WHERE tenant_id = $1
ORDER BY created_at DESC
`

// FindCustomersByTenant
//
//	SELECT id, tenant_id, phone_number, name, is_blocked, created_at
//	FROM customers
//	WHERE tenant_id = $1
//	ORDER BY created_at DESC
func (q *Queries) FindCustomersByTenant(ctx context.Context, db DBTX, tenantID uuid.UUID) ([]Customer, error) {
	rows, err := db.QueryContext(ctx, findCustomersByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PhoneNumber,
			&i.Name,
			&i.IsBlocked,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
