// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers_update.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const updateCustomer = `-- name: UpdateCustomer :exec
UPDATE customers
SET name = $1
WHERE id = $2
`

type UpdateCustomerParams struct {
	Name sql.NullString `db:"name"`
	ID   uuid.UUID      `db:"id"`
}

// UpdateCustomer
//
//	UPDATE customers
//	SET name = $1
//	WHERE id = $2
func (q *Queries) UpdateCustomer(ctx context.Context, db DBTX, arg UpdateCustomerParams) error {
	_, err := db.ExecContext(ctx, updateCustomer, arg.Name, arg.ID)
	return err
}
