// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers_increment_no_shows.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const incrementCustomerNoShows = `-- name: IncrementCustomerNoShows :exec
UPDATE customers
SET no_show_count = no_show_count + 1
WHERE id = $1 AND tenant_id = $2
`

type IncrementCustomerNoShowsParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

// IncrementCustomerNoShows
//
//	UPDATE customers
//	SET no_show_count = no_show_count + 1
//	WHERE id = $1 AND tenant_id = $2
func (q *Queries) IncrementCustomerNoShows(ctx context.Context, db DBTX, arg IncrementCustomerNoShowsParams) error {
	_, err := db.ExecContext(ctx, incrementCustomerNoShows, arg.ID, arg.TenantID)
	return err
}
