// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers_find_by_id.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const findCustomerByID = `-- name: FindCustomerByID :one
SELECT id, tenant_id, phone_number, name, is_blocked, created_at
FROM customers
WHERE id = $1
LIMIT 1
`

// FindCustomerByID
//
//	SELECT id, tenant_id, phone_number, name, is_blocked, created_at
//	FROM customers
//	WHERE id = $1
//	LIMIT 1
func (q *Queries) FindCustomerByID(ctx context.Context, db DBTX, id uuid.UUID) (Customer, error) {
	row := db.QueryRowContext(ctx, findCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PhoneNumber,
		&i.Name,
		&i.IsBlocked,
		&i.CreatedAt,
	)
	return i, err
}
