// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers_find_by_tenant.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const findCustomersByTenant = `-- name: FindCustomersByTenant :many
SELECT id,
       tenant_id,
       phone_number,
       name,
       is_blocked,
       created_at,
       no_show_count,
       late_cancel_count
FROM customers
WHERE tenant_id = $1
ORDER BY created_at DESC
`

type FindCustomersByTenantRow struct {
	ID              uuid.UUID      `db:"id"`
	TenantID        uuid.UUID      `db:"tenant_id"`
	PhoneNumber     string         `db:"phone_number"`
	Name            sql.NullString `db:"name"`
	IsBlocked       bool           `db:"is_blocked"`
	CreatedAt       time.Time      `db:"created_at"`
	NoShowCount     int32          `db:"no_show_count"`
	LateCancelCount int32          `db:"late_cancel_count"`
}

// FindCustomersByTenant
//
//	SELECT id,
//	       tenant_id,
//	       phone_number,
//	       name,
//	       is_blocked,
//	       created_at,
//	       no_show_count,
//	       late_cancel_count
//	FROM customers
//	WHERE tenant_id = $1
//	ORDER BY created_at DESC
func (q *Queries) FindCustomersByTenant(ctx context.Context, db DBTX, tenantID uuid.UUID) ([]FindCustomersByTenantRow, error) {
	rows, err := db.QueryContext(ctx, findCustomersByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindCustomersByTenantRow
	for rows.Next() {
		var i FindCustomersByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PhoneNumber,
			&i.Name,
			&i.IsBlocked,
			&i.CreatedAt,
			&i.NoShowCount,
			&i.LateCancelCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
