// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers_increment_late_cancels.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const incrementCustomerLateCancels = `-- name: IncrementCustomerLateCancels :exec
UPDATE customers
SET late_cancel_count = late_cancel_count + 1
WHERE id = $1 AND tenant_id = $2
`

type IncrementCustomerLateCancelsParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

// IncrementCustomerLateCancels
//
//	UPDATE customers
//	SET late_cancel_count = late_cancel_count + 1
//	WHERE id = $1 AND tenant_id = $2
func (q *Queries) IncrementCustomerLateCancels(ctx context.Context, db DBTX, arg IncrementCustomerLateCancelsParams) error {
	_, err := db.ExecContext(ctx, incrementCustomerLateCancels, arg.ID, arg.TenantID)
	return err
}
