// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers_count_late_cancels.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countCustomerLateCancels = `-- name: CountCustomerLateCancels :one
SELECT COUNT(*) as late_cancels
FROM appointments
WHERE status = 'cancelled'
  AND tenant_id = $1
  AND customer_id = $2
  AND cancelled_at IS NOT NULL
  AND EXTRACT(EPOCH FROM (starts_at - cancelled_at)) / 3600 < $3::int
`

type CountCustomerLateCancelsParams struct {
	TenantID   uuid.UUID `db:"tenant_id"`
	CustomerID uuid.UUID `db:"customer_id"`
	LateHours  int32     `db:"late_hours"`
}

// CountCustomerLateCancels
//
//	SELECT COUNT(*) as late_cancels
//	FROM appointments
//	WHERE status = 'cancelled'
//	  AND tenant_id = $1
//	  AND customer_id = $2
//	  AND cancelled_at IS NOT NULL
//	  AND EXTRACT(EPOCH FROM (starts_at - cancelled_at)) / 3600 < $3::int
func (q *Queries) CountCustomerLateCancels(ctx context.Context, db DBTX, arg CountCustomerLateCancelsParams) (int64, error) {
	row := db.QueryRowContext(ctx, countCustomerLateCancels, arg.TenantID, arg.CustomerID, arg.LateHours)
	var late_cancels int64
	err := row.Scan(&late_cancels)
	return late_cancels, err
}
