// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers_find_by_phone_number.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const findCustomerByPhoneNumber = `-- name: FindCustomerByPhoneNumber :one
SELECT id, tenant_id, phone_number, name, is_blocked, created_at
FROM customers
WHERE tenant_id = $1
  AND phone_number = $2
LIMIT 1
`

type FindCustomerByPhoneNumberParams struct {
	TenantID    uuid.UUID `db:"tenant_id"`
	PhoneNumber string    `db:"phone_number"`
}

// FindCustomerByPhoneNumber
//
//	SELECT id, tenant_id, phone_number, name, is_blocked, created_at
//	FROM customers
//	WHERE tenant_id = $1
//	  AND phone_number = $2
//	LIMIT 1
func (q *Queries) FindCustomerByPhoneNumber(ctx context.Context, db DBTX, arg FindCustomerByPhoneNumberParams) (Customer, error) {
	row := db.QueryRowContext(ctx, findCustomerByPhoneNumber, arg.TenantID, arg.PhoneNumber)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PhoneNumber,
		&i.Name,
		&i.IsBlocked,
		&i.CreatedAt,
	)
	return i, err
}
