// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers_count_no_shows.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countCustomerNoShows = `-- name: CountCustomerNoShows :one
SELECT no_show_count AS no_shows
FROM customers
WHERE id = $1
  AND tenant_id = $2
`

type CountCustomerNoShowsParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

// CountCustomerNoShows
//
//	SELECT no_show_count AS no_shows
//	FROM customers
//	WHERE id = $1
//	  AND tenant_id = $2
func (q *Queries) CountCustomerNoShows(ctx context.Context, db DBTX, arg CountCustomerNoShowsParams) (int32, error) {
	row := db.QueryRowContext(ctx, countCustomerNoShows, arg.ID, arg.TenantID)
	var no_shows int32
	err := row.Scan(&no_shows)
	return no_shows, err
}
