// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers_insert.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertCustomer = `-- name: InsertCustomer :exec
INSERT INTO customers (id, tenant_id, phone_number)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id, phone_number) DO NOTHING
`

type InsertCustomerParams struct {
	ID          uuid.UUID `db:"id"`
	TenantID    uuid.UUID `db:"tenant_id"`
	PhoneNumber string    `db:"phone_number"`
}

// InsertCustomer
//
//	INSERT INTO customers (id, tenant_id, phone_number)
//	VALUES ($1, $2, $3)
//	ON CONFLICT (tenant_id, phone_number) DO NOTHING
func (q *Queries) InsertCustomer(ctx context.Context, db DBTX, arg InsertCustomerParams) error {
	_, err := db.ExecContext(ctx, insertCustomer, arg.ID, arg.TenantID, arg.PhoneNumber)
	return err
}
