// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers_block.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const blockCustomer = `-- name: BlockCustomer :exec
UPDATE customers
SET is_blocked = true
WHERE id = $1
  AND tenant_id = $2
`

type BlockCustomerParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

// BlockCustomer
//
//	UPDATE customers
//	SET is_blocked = true
//	WHERE id = $1
//	  AND tenant_id = $2
func (q *Queries) BlockCustomer(ctx context.Context, db DBTX, arg BlockCustomerParams) error {
	_, err := db.ExecContext(ctx, blockCustomer, arg.ID, arg.TenantID)
	return err
}
