// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers_count_late_cancels.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countCustomerLateCancels = `-- name: CountCustomerLateCancels :one
SELECT late_cancel_count AS late_cancels
FROM customers
WHERE id = $1
  AND tenant_id = $2
`

type CountCustomerLateCancelsParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

// CountCustomerLateCancels
//
//	SELECT late_cancel_count AS late_cancels
//	FROM customers
//	WHERE id = $1
//	  AND tenant_id = $2
func (q *Queries) CountCustomerLateCancels(ctx context.Context, db DBTX, arg CountCustomerLateCancelsParams) (int32, error) {
	row := db.QueryRowContext(ctx, countCustomerLateCancels, arg.ID, arg.TenantID)
	var late_cancels int32
	err := row.Scan(&late_cancels)
	return late_cancels, err
}
