// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers_count_no_shows.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countCustomerNoShows = `-- name: CountCustomerNoShows :one
SELECT COUNT(*) as no_shows
FROM appointments
WHERE tenant_id = $1
  AND customer_id = $2
  AND status = 'no_show'
`

type CountCustomerNoShowsParams struct {
	TenantID   uuid.UUID `db:"tenant_id"`
	CustomerID uuid.UUID `db:"customer_id"`
}

// CountCustomerNoShows
//
//	SELECT COUNT(*) as no_shows
//	FROM appointments
//	WHERE tenant_id = $1
//	  AND customer_id = $2
//	  AND status = 'no_show'
func (q *Queries) CountCustomerNoShows(ctx context.Context, db DBTX, arg CountCustomerNoShowsParams) (int64, error) {
	row := db.QueryRowContext(ctx, countCustomerNoShows, arg.TenantID, arg.CustomerID)
	var no_shows int64
	err := row.Scan(&no_shows)
	return no_shows, err
}
