// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jwks_find_by_id.sql

package db

import (
	"context"
)

const findJWKByID = `-- name: FindJWKByID :one
SELECT id, public_key
FROM jwks
WHERE id = $1
  AND (expires_at IS NULL OR expires_at > NOW())
LIMIT 1
`

type FindJWKByIDRow struct {
	ID        string `db:"id"`
	PublicKey string `db:"public_key"`
}

// FindJWKByID
//
//	SELECT id, public_key
//	FROM jwks
//	WHERE id = $1
//	  AND (expires_at IS NULL OR expires_at > NOW())
//	LIMIT 1
func (q *Queries) FindJWKByID(ctx context.Context, db DBTX, id string) (FindJWKByIDRow, error) {
	row := db.QueryRowContext(ctx, findJWKByID, id)
	var i FindJWKByIDRow
	err := row.Scan(&i.ID, &i.PublicKey)
	return i, err
}
