// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: onboarding_progress_find_by_tenant.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const findOnboardingProgressByTenant = `-- name: FindOnboardingProgressByTenant :one
SELECT id, tenant_id, current_step, completed_at, created_at, updated_at
FROM onboarding_progress
WHERE tenant_id = $1
LIMIT 1
`

type FindOnboardingProgressByTenantRow struct {
	ID          uuid.UUID    `db:"id"`
	TenantID    uuid.UUID    `db:"tenant_id"`
	CurrentStep int32        `db:"current_step"`
	CompletedAt sql.NullTime `db:"completed_at"`
	CreatedAt   time.Time    `db:"created_at"`
	UpdatedAt   time.Time    `db:"updated_at"`
}

// FindOnboardingProgressByTenant
//
//	SELECT id, tenant_id, current_step, completed_at, created_at, updated_at
//	FROM onboarding_progress
//	WHERE tenant_id = $1
//	LIMIT 1
func (q *Queries) FindOnboardingProgressByTenant(ctx context.Context, db DBTX, tenantID uuid.UUID) (FindOnboardingProgressByTenantRow, error) {
	row := db.QueryRowContext(ctx, findOnboardingProgressByTenant, tenantID)
	var i FindOnboardingProgressByTenantRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CurrentStep,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
