// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plans_find_by_external_id.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const findPlanByExternalId = `-- name: FindPlanByExternalId :one
SELECT id,
       external_id,
       name,
       description,
       price,
       currency,
       "interval"
FROM plans
WHERE is_active = true
    AND external_id = $1 AND environment = $2
`

type FindPlanByExternalIdParams struct {
	ExternalID  string `db:"external_id"`
	Environment string `db:"environment"`
}

type FindPlanByExternalIdRow struct {
	ID          uuid.UUID      `db:"id"`
	ExternalID  string         `db:"external_id"`
	Name        string         `db:"name"`
	Description sql.NullString `db:"description"`
	Price       int32          `db:"price"`
	Currency    string         `db:"currency"`
	Interval    sql.NullString `db:"interval"`
}

// FindPlanByExternalId
//
//	SELECT id,
//	       external_id,
//	       name,
//	       description,
//	       price,
//	       currency,
//	       "interval"
//	FROM plans
//	WHERE is_active = true
//	    AND external_id = $1 AND environment = $2
func (q *Queries) FindPlanByExternalId(ctx context.Context, db DBTX, arg FindPlanByExternalIdParams) (FindPlanByExternalIdRow, error) {
	row := db.QueryRowContext(ctx, findPlanByExternalId, arg.ExternalID, arg.Environment)
	var i FindPlanByExternalIdRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Currency,
		&i.Interval,
	)
	return i, err
}
