// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	//ActivateTenantWhatsappConfig
	//
	//  UPDATE tenant_whatsapp_configs
	//  SET waba_id              = $1,
	//      phone_number_id      = $2,
	//      display_phone_number = $3,
	//      access_token         = $4,
	//      activation_status    = 'active',
	//      is_active            = true,
	//      verified_at          = NOW()
	//  WHERE tenant_id = $5
	ActivateTenantWhatsappConfig(ctx context.Context, db DBTX, arg ActivateTenantWhatsappConfigParams) error
	//AdvanceOnboardingStep
	//
	//  UPDATE onboarding_progress
	//  SET current_step = current_step + 1,
	//      updated_at   = NOW()
	//  WHERE tenant_id = $1
	//    AND current_step < $2
	AdvanceOnboardingStep(ctx context.Context, db DBTX, arg AdvanceOnboardingStepParams) error
	//BlockCustomer
	//
	//  UPDATE customers
	//  SET is_blocked = true
	//  WHERE id = $1
	//    AND tenant_id = $2
	BlockCustomer(ctx context.Context, db DBTX, arg BlockCustomerParams) error
	//ClaimDueAppointmentReminderEvents
	//
	//  INSERT INTO appointment_reminder_events(
	//      id,
	//      appointment_id,
	//      tenant_id,
	//      customer_id,
	//      reminder_type,
	//      attempts,
	//      created_at
	//  )
	//  SELECT gen_random_uuid(),
	//         a.id,
	//         a.tenant_id,
	//         a.customer_id,
	//         CASE
	//             WHEN a.reminder_24h_sent_at IS NULL
	//                 AND a.starts_at BETWEEN NOW() + INTERVAL '23 hours' AND NOW() + INTERVAL '25 hours'
	//                 THEN '24h'
	//             WHEN a.reminder_1h_sent_at IS NULL
	//                 AND a.starts_at BETWEEN NOW() + INTERVAL '50 minutes' AND NOW() + INTERVAL '70 minutes'
	//                 THEN '1h'
	//             ELSE NULL
	//             END AS reminder_type,
	//         0,
	//         NOW()
	//  FROM appointments a
	//  WHERE a.status = 'confirmed'
	//    AND (
	//      (a.reminder_24h_sent_at IS NULL AND a.starts_at BETWEEN NOW() + INTERVAL '23 hours' AND NOW() + INTERVAL '25 hours')
	//          OR
	//      (a.reminder_1h_sent_at IS NULL AND a.starts_at BETWEEN NOW() + INTERVAL '50 minutes' AND NOW() + INTERVAL '70 minutes')
	//      )
	//  ON CONFLICT (appointment_id, reminder_type) DO NOTHING
	ClaimDueAppointmentReminderEvents(ctx context.Context, db DBTX) error
	//CompleteOnboardingProgress
	//
	//  UPDATE onboarding_progress
	//  SET completed_at = NOW(),
	//      updated_at   = NOW()
	//  WHERE tenant_id = $1
	CompleteOnboardingProgress(ctx context.Context, db DBTX, tenantID uuid.UUID) error
	//CountCustomerLateCancels
	//
	//  SELECT late_cancel_count AS late_cancels
	//  FROM customers
	//  WHERE id = $1
	//    AND tenant_id = $2
	CountCustomerLateCancels(ctx context.Context, db DBTX, arg CountCustomerLateCancelsParams) (int32, error)
	//CountCustomerNoShows
	//
	//  SELECT no_show_count AS no_shows
	//  FROM customers
	//  WHERE id = $1
	//    AND tenant_id = $2
	CountCustomerNoShows(ctx context.Context, db DBTX, arg CountCustomerNoShowsParams) (int32, error)
	//DeleteConversationSession
	//
	//  DELETE
	//  FROM conversation_sessions
	//  WHERE id = $1
	DeleteConversationSession(ctx context.Context, db DBTX, id uuid.UUID) error
	//DeleteExpiredConversationSessions
	//
	//  DELETE
	//  FROM conversation_sessions
	//  WHERE expires_at < NOW()
	DeleteExpiredConversationSessions(ctx context.Context, db DBTX) error
	//DeleteResource
	//
	//  UPDATE resources
	//  SET is_active = false
	//  WHERE id = $1
	//    AND tenant_id = $2
	DeleteResource(ctx context.Context, db DBTX, arg DeleteResourceParams) error
	//DeleteResourceService
	//
	//  DELETE
	//  FROM resource_services
	//  WHERE resource_id = $1
	DeleteResourceService(ctx context.Context, db DBTX, resourceID uuid.UUID) error
	//DeleteScheduleOverride
	//
	//  DELETE
	//  FROM schedule_overrides
	//  WHERE id = $1
	//    AND resource_id = $2
	DeleteScheduleOverride(ctx context.Context, db DBTX, arg DeleteScheduleOverrideParams) error
	//DeleteService
	//
	//  UPDATE services
	//  SET is_active = false
	//  WHERE id = $1
	//    AND tenant_id = $2
	DeleteService(ctx context.Context, db DBTX, arg DeleteServiceParams) error
	//DeleteWorkingHour
	//
	//  DELETE
	//  FROM working_hours
	//  WHERE id = $1
	//    AND resource_id = $2
	DeleteWorkingHour(ctx context.Context, db DBTX, arg DeleteWorkingHourParams) error
	//FindAppointmentByID
	//
	//  SELECT id,
	//         tenant_id,
	//         resource_id,
	//         service_id,
	//         customer_id,
	//         starts_at,
	//         ends_at,
	//         status,
	//         price_at_booking
	//  FROM appointments
	//  WHERE id = $1
	//    AND tenant_id = $2
	//  LIMIT 1
	FindAppointmentByID(ctx context.Context, db DBTX, arg FindAppointmentByIDParams) (FindAppointmentByIDRow, error)
	//FindAppointmentStatusHistory
	//
	//  SELECT h.id,
	//         h.appointment_id,
	//         h.from_status,
	//         h.to_status,
	//         u.name as changed_by,
	//         h.changed_by_role,
	//         h.reason,
	//         h.created_at
	//  FROM appointment_status_history h
	//           JOIN appointments a ON a.id = h.appointment_id
	//           LEFT JOIN users u ON u.id = h.changed_by
	//  WHERE h.appointment_id = $1
	//    AND a.tenant_id = $2
	//  ORDER BY h.created_at
	FindAppointmentStatusHistory(ctx context.Context, db DBTX, arg FindAppointmentStatusHistoryParams) ([]FindAppointmentStatusHistoryRow, error)
	//FindAppointmentsByCustomerID
	//
	//  SELECT a.id,
	//         a.starts_at,
	//         a.ends_at,
	//         a.status,
	//         a.price_at_booking,
	//         r.name AS resource_name,
	//         s.name AS service_name
	//  FROM appointments a
	//           JOIN resources r ON r.id = a.resource_id
	//           JOIN services s ON s.id = a.service_id
	//  WHERE a.tenant_id = $1
	//    AND a.customer_id = $2
	//    AND a.status = 'confirmed'
	//    AND a.starts_at > NOW()
	//  ORDER BY a.starts_at
	//  LIMIT 5
	FindAppointmentsByCustomerID(ctx context.Context, db DBTX, arg FindAppointmentsByCustomerIDParams) ([]FindAppointmentsByCustomerIDRow, error)
	//FindCustomerActiveConversationSession
	//
	//  SELECT id,
	//         tenant_id,
	//         whatsapp_config_id,
	//         customer_id,
	//         step,
	//         data,
	//         expires_at,
	//         created_at,
	//         updated_at
	//  FROM conversation_sessions
	//  WHERE tenant_id = $1
	//    AND customer_id = $2
	//    AND expires_at > NOW()
	//  LIMIT 1
	FindCustomerActiveConversationSession(ctx context.Context, db DBTX, arg FindCustomerActiveConversationSessionParams) (ConversationSession, error)
	//FindCustomerByID
	//
	//  SELECT id, tenant_id, phone_number, name, is_blocked, created_at
	//  FROM customers
	//  WHERE id = $1
	//  LIMIT 1
	FindCustomerByID(ctx context.Context, db DBTX, id uuid.UUID) (FindCustomerByIDRow, error)
	//FindCustomerByPhoneNumber
	//
	//  SELECT id, tenant_id, phone_number, name, is_blocked, created_at
	//  FROM customers
	//  WHERE tenant_id = $1
	//    AND phone_number = $2
	//  LIMIT 1
	FindCustomerByPhoneNumber(ctx context.Context, db DBTX, arg FindCustomerByPhoneNumberParams) (FindCustomerByPhoneNumberRow, error)
	//FindCustomerPenaltyCounts
	//
	//  SELECT no_show_count,
	//         late_cancel_count
	//  FROM customers
	//  WHERE id = $1
	//    AND tenant_id = $2
	FindCustomerPenaltyCounts(ctx context.Context, db DBTX, arg FindCustomerPenaltyCountsParams) (FindCustomerPenaltyCountsRow, error)
	//FindCustomersByTenant
	//
	//  SELECT id,
	//         tenant_id,
	//         phone_number,
	//         name,
	//         is_blocked,
	//         created_at,
	//         no_show_count,
	//         late_cancel_count
	//  FROM customers
	//  WHERE tenant_id = $1
	//  ORDER BY created_at DESC
	FindCustomersByTenant(ctx context.Context, db DBTX, tenantID uuid.UUID) ([]Customer, error)
	//FindOnboardingProgressByTenant
	//
	//  SELECT id, tenant_id, current_step, completed_at, created_at, updated_at
	//  FROM onboarding_progress
	//  WHERE tenant_id = $1
	//  LIMIT 1
	FindOnboardingProgressByTenant(ctx context.Context, db DBTX, tenantID uuid.UUID) (OnboardingProgress, error)
	//FindPendingAppointmentReminderEvents
	//
	//  SELECT e.id,
	//         e.appointment_id,
	//         e.tenant_id,
	//         e.customer_id,
	//         e.reminder_type,
	//         e.attempts,
	//         a.starts_at
	//  FROM appointment_reminder_events e
	//           JOIN appointments a ON a.id = e.appointment_id
	//  WHERE e.sent_at IS NULL
	//    AND e.attempts < 5
	//    AND a.status = 'confirmed'
	//  ORDER BY e.created_at
	//  LIMIT 500
	FindPendingAppointmentReminderEvents(ctx context.Context, db DBTX) ([]FindPendingAppointmentReminderEventsRow, error)
	//FindRecentlyCancelledAppointments
	//
	//  SELECT id,
	//         tenant_id,
	//         customer_id,
	//         resource_id,
	//         service_id,
	//         starts_at,
	//         ends_at,
	//         status,
	//         cancelled_at
	//  FROM appointments
	//  WHERE status = 'cancelled'
	//    AND cancelled_at IS NOT NULL
	//    AND cancelled_at >= NOW() - INTERVAL '10 minutes'
	FindRecentlyCancelledAppointments(ctx context.Context, db DBTX) ([]FindRecentlyCancelledAppointmentsRow, error)
	//FindResourceById
	//
	//  SELECT id,
	//         tenant_id,
	//         name,
	//         type,
	//         COALESCE(avatar_url, '') as avatar_url,
	//         is_active,
	//         sort_order,
	//         created_at
	//  FROM resources
	//  WHERE id = $1
	//    AND is_active = true
	//  LIMIT 1
	FindResourceById(ctx context.Context, db DBTX, id uuid.UUID) (FindResourceByIdRow, error)
	//FindResourceOccupiedSlots
	//
	//  SELECT a.starts_at, a.ends_at, r.name AS resource_name
	//  FROM appointments a
	//           INNER JOIN resources r ON a.resource_id = r.id
	//  WHERE resource_id = $1
	//    AND starts_at >= $2
	//    AND ends_at <= $3
	//    AND status NOT IN ('cancelled', 'no_show')
	//  ORDER BY starts_at
	FindResourceOccupiedSlots(ctx context.Context, db DBTX, arg FindResourceOccupiedSlotsParams) ([]FindResourceOccupiedSlotsRow, error)
	//FindResourceScheduleOverrides
	//
	//  SELECT id,
	//         resource_id,
	//         date,
	//         is_day_off,
	//         start_time,
	//         end_time,
	//         COALESCE(reason, '') as reason,
	//         created_at
	//  FROM schedule_overrides
	//  WHERE resource_id = $1
	//    AND date BETWEEN $2 AND $3
	//  ORDER BY date
	FindResourceScheduleOverrides(ctx context.Context, db DBTX, arg FindResourceScheduleOverridesParams) ([]FindResourceScheduleOverridesRow, error)
	//FindResourceWorkingHours
	//
	//  SELECT id,
	//         resource_id,
	//         day_of_week,
	//         start_time::text,
	//         end_time::text,
	//         is_active
	//  FROM working_hours
	//  WHERE resource_id = $1
	//  ORDER BY day_of_week
	FindResourceWorkingHours(ctx context.Context, db DBTX, resourceID uuid.UUID) ([]FindResourceWorkingHoursRow, error)
	//FindResourcesByServiceID
	//
	//  SELECT r.id,
	//         r.tenant_id,
	//         r.name,
	//         r.type,
	//         COALESCE(r.avatar_url, '') as avatar_url,
	//         r.is_active,
	//         r.sort_order,
	//         r.created_at
	//  FROM resources r
	//           JOIN resource_services rs ON rs.resource_id = r.id
	//  WHERE r.tenant_id = $1
	//    AND rs.service_id = $2
	//    AND r.is_active = true
	//  ORDER BY r.created_at
	FindResourcesByServiceID(ctx context.Context, db DBTX, arg FindResourcesByServiceIDParams) ([]FindResourcesByServiceIDRow, error)
	//FindResourcesByTenant
	//
	//  SELECT id,
	//         tenant_id,
	//         name,
	//         type,
	//         COALESCE(avatar_url, '') as avatar_url,
	//         is_active,
	//         sort_order,
	//         created_at
	//  FROM resources
	//  WHERE tenant_id = $1
	//    AND is_active = true
	//  ORDER BY created_at
	FindResourcesByTenant(ctx context.Context, db DBTX, tenantID uuid.UUID) ([]FindResourcesByTenantRow, error)
	//FindServiceByID
	//
	//  SELECT id,
	//         tenant_id,
	//         name,
	//         description,
	//         duration_minutes,
	//         buffer_minutes,
	//         price,
	//         is_active,
	//         sort_order,
	//         created_at
	//  FROM services
	//  WHERE id = $1
	//    AND is_active = true
	FindServiceByID(ctx context.Context, db DBTX, id uuid.UUID) (Service, error)
	//FindServicesByResourceID
	//
	//  SELECT s.id,
	//         s.tenant_id,
	//         s.name,
	//         s.description,
	//         s.duration_minutes,
	//         s.buffer_minutes,
	//         s.price,
	//         s.is_active,
	//         s.sort_order,
	//         s.created_at
	//  FROM services s
	//           JOIN resource_services rs ON rs.service_id = s.id
	//  WHERE s.tenant_id = $1
	//    AND rs.resource_id = $2
	//    AND s.is_active = true
	//  ORDER BY s.created_at
	FindServicesByResourceID(ctx context.Context, db DBTX, arg FindServicesByResourceIDParams) ([]Service, error)
	//FindServicesByTenantID
	//
	//  SELECT id,
	//         tenant_id,
	//         name,
	//         description,
	//         duration_minutes,
	//         buffer_minutes,
	//         price,
	//         is_active,
	//         sort_order,
	//         created_at
	//  FROM services
	//  WHERE tenant_id = $1
	//    AND is_active = true
	//  ORDER BY created_at
	FindServicesByTenantID(ctx context.Context, db DBTX, tenantID uuid.UUID) ([]Service, error)
	//FindServicesWithAssignedResourceByTenantID
	//
	//  SELECT DISTINCT s.id,
	//                  s.tenant_id,
	//                  s.name,
	//                  s.description,
	//                  s.duration_minutes,
	//                  s.buffer_minutes,
	//                  s.price,
	//                  s.is_active,
	//                  s.sort_order,
	//                  s.created_at
	//  FROM services s
	//           JOIN resource_services rs ON rs.service_id = s.id
	//           JOIN resources r ON r.id = rs.resource_id AND r.is_active = true
	//  WHERE s.tenant_id = $1
	//    AND s.is_active = true
	//  ORDER BY s.created_at
	FindServicesWithAssignedResourceByTenantID(ctx context.Context, db DBTX, tenantID uuid.UUID) ([]Service, error)
	//FindTenantByID
	//
	//  SELECT id,
	//         name,
	//         slug,
	//         timezone,
	//         currency,
	//         plan,
	//         plan_expires_at,
	//         appointments_this_month,
	//         month_reset_at,
	//         is_active,
	//         settings,
	//         created_at,
	//         updated_at
	//  FROM tenants
	//  WHERE id = $1
	//    AND is_active = true
	//  LIMIT 1
	FindTenantByID(ctx context.Context, db DBTX, id uuid.UUID) (Tenant, error)
	//FindTenantBySlug
	//
	//  SELECT id,
	//         name,
	//         slug,
	//         timezone,
	//         currency,
	//         plan,
	//         plan_expires_at,
	//         appointments_this_month,
	//         month_reset_at,
	//         is_active,
	//         settings,
	//         created_at,
	//         updated_at
	//  FROM tenants
	//  WHERE slug = $1
	//    AND is_active = true
	//  LIMIT 1
	FindTenantBySlug(ctx context.Context, db DBTX, slug string) (Tenant, error)
	//FindTenantByUserId
	//
	//  SELECT t.id,
	//         t.name,
	//         t.slug,
	//         t.timezone,
	//         t.currency,
	//         t.plan,
	//         t.plan_expires_at,
	//         t.appointments_this_month,
	//         t.month_reset_at,
	//         t.is_active,
	//         t.settings,
	//         t.created_at,
	//         t.updated_at
	//  FROM tenants t
	//           JOIN tenant_users tu ON tu.tenant_id = t.id
	//  WHERE tu.user_id = $1
	//    AND t.is_active = true
	//  LIMIT 1
	FindTenantByUserId(ctx context.Context, db DBTX, userID string) (Tenant, error)
	//FindTenantPendingActivations
	//
	//  SELECT wc.tenant_id,
	//         t.name                                    AS tenant_name,
	//         COALESCE(wc.activation_contact_email, '') AS contact_email,
	//         wc.activation_status,
	//         wc.activation_requested_at,
	//         COALESCE(wc.activation_notes, '')         AS activation_notes
	//  FROM tenant_whatsapp_configs wc
	//           JOIN tenants t ON t.id = wc.tenant_id
	//  WHERE wc.activation_status = 'pending'
	//  ORDER BY wc.activation_requested_at
	FindTenantPendingActivations(ctx context.Context, db DBTX) ([]FindTenantPendingActivationsRow, error)
	//FindTenantWhatsappConfig
	//
	//  SELECT id,
	//         tenant_id,
	//         waba_id,
	//         phone_number_id,
	//         display_phone_number,
	//         access_token,
	//         token_expires_at,
	//         is_active,
	//         activation_contact_email,
	//         verified_at,
	//         created_at,
	//         updated_at
	//  FROM tenant_whatsapp_configs
	//  WHERE tenant_id = $1
	//    AND is_active = true
	//  LIMIT 1
	FindTenantWhatsappConfig(ctx context.Context, db DBTX, tenantID uuid.UUID) (FindTenantWhatsappConfigRow, error)
	//FindTenantWhatsappConfigByPhoneNumberID
	//
	//  SELECT twc.id,
	//         twc.tenant_id,
	//         twc.waba_id,
	//         twc.phone_number_id,
	//         twc.display_phone_number,
	//         twc.access_token,
	//         twc.token_expires_at,
	//         twc.is_active,
	//         twc.verified_at,
	//         twc.created_at,
	//         twc.updated_at,
	//         t.name      AS tenant_name,
	//         t.slug      AS tenant_slug,
	//         t.timezone  AS tenant_timezone,
	//         t.currency  AS tenant_currency,
	//         t.plan      AS tenant_plan,
	//         t.settings  AS tenant_settings,
	//         t.is_active AS tenant_active,
	//         t.month_reset_at,
	//         t.appointments_this_month
	//  FROM tenant_whatsapp_configs twc
	//           JOIN tenants t ON t.id = twc.tenant_id
	//  WHERE twc.phone_number_id = $1
	//    AND twc.is_active = true
	//    AND t.is_active = true
	//  LIMIT 1
	FindTenantWhatsappConfigByPhoneNumberID(ctx context.Context, db DBTX, phoneNumberID sql.NullString) (FindTenantWhatsappConfigByPhoneNumberIDRow, error)
	//FindUnattendedAppointments
	//
	//  SELECT id,
	//         tenant_id,
	//         customer_id,
	//         resource_id,
	//         service_id,
	//         starts_at,
	//         ends_at,
	//         status
	//  FROM appointments
	//  WHERE status = 'confirmed'
	//    AND starts_at <= NOW() - INTERVAL '30 minutes'
	FindUnattendedAppointments(ctx context.Context, db DBTX) ([]FindUnattendedAppointmentsRow, error)
	//FindUpcomingAppointments
	//
	//  SELECT id, tenant_id, customer_id, resource_id, service_id, starts_at, ends_at
	//  FROM appointments
	//  WHERE status = 'confirmed'
	//    AND (
	//      (reminder_24h_sent_at IS NULL AND starts_at BETWEEN NOW() + INTERVAL '23 hours' AND NOW() + INTERVAL '25 hours')
	//          OR
	//      (reminder_1h_sent_at IS NULL AND starts_at BETWEEN NOW() + INTERVAL '50 minutes' AND NOW() + INTERVAL '70 minutes')
	//      )
	FindUpcomingAppointments(ctx context.Context, db DBTX) ([]FindUpcomingAppointmentsRow, error)
	//IncrementCustomerLateCancels
	//
	//  UPDATE customers
	//  SET late_cancel_count = late_cancel_count + 1
	//  WHERE id = $1 AND tenant_id = $2
	IncrementCustomerLateCancels(ctx context.Context, db DBTX, arg IncrementCustomerLateCancelsParams) error
	//IncrementCustomerNoShows
	//
	//  UPDATE customers
	//  SET no_show_count = no_show_count + 1
	//  WHERE id = $1 AND tenant_id = $2
	IncrementCustomerNoShows(ctx context.Context, db DBTX, arg IncrementCustomerNoShowsParams) error
	//IncrementCustomersLateCancelsBatch
	//
	//  WITH args AS (
	//      SELECT
	//          $1::uuid[] AS customer_ids,
	//          $2::uuid[] AS tenant_ids,
	//          $3::int[] AS increments
	//  ),
	//  updates AS (
	//      SELECT
	//          UNNEST(args.customer_ids) AS customer_id,
	//          UNNEST(args.tenant_ids) AS tenant_id,
	//          UNNEST(args.increments) AS increment_by
	//      FROM args
	//  )
	//  UPDATE customers AS c
	//  SET late_cancel_count = c.late_cancel_count + updates.increment_by
	//  FROM updates
	//  WHERE c.id = updates.customer_id
	//    AND c.tenant_id = updates.tenant_id
	IncrementCustomersLateCancelsBatch(ctx context.Context, db DBTX, arg IncrementCustomersLateCancelsBatchParams) error
	//IncrementCustomersNoShowsBatch
	//
	//  WITH args AS (
	//      SELECT
	//          $1::uuid[] AS customer_ids,
	//          $2::uuid[] AS tenant_ids,
	//          $3::int[] AS increments
	//  ),
	//  updates AS (
	//      SELECT
	//          UNNEST(args.customer_ids) AS customer_id,
	//          UNNEST(args.tenant_ids) AS tenant_id,
	//          UNNEST(args.increments) AS increment_by
	//      FROM args
	//  )
	//  UPDATE customers AS c
	//  SET no_show_count = c.no_show_count + updates.increment_by
	//  FROM updates
	//  WHERE c.id = updates.customer_id
	//    AND c.tenant_id = updates.tenant_id
	IncrementCustomersNoShowsBatch(ctx context.Context, db DBTX, arg IncrementCustomersNoShowsBatchParams) error
	//InsertAppointment
	//
	//  INSERT INTO appointments(
	//      id,
	//      tenant_id,
	//      resource_id,
	//      service_id,
	//      customer_id,
	//      starts_at,
	//      ends_at,
	//      status,
	//      price_at_booking
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7,
	//      'confirmed',
	//      $8
	//  )
	InsertAppointment(ctx context.Context, db DBTX, arg InsertAppointmentParams) error
	//InsertAppointmentPenaltyEvent
	//
	//  INSERT INTO appointment_penalty_events(
	//      id,
	//      appointment_id,
	//      tenant_id,
	//      customer_id,
	//      event_type,
	//      occurred_at,
	//      created_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      NOW()
	//  )
	//  ON CONFLICT (appointment_id, event_type) DO NOTHING
	InsertAppointmentPenaltyEvent(ctx context.Context, db DBTX, arg InsertAppointmentPenaltyEventParams) (int64, error)
	//InsertAppointmentStatusHistory
	//
	//  INSERT INTO appointment_status_history(
	//      id,
	//      appointment_id,
	//      from_status,
	//      to_status,
	//      changed_by,
	//      changed_by_role,
	//      reason,
	//      created_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7,
	//      NOW()
	//  )
	InsertAppointmentStatusHistory(ctx context.Context, db DBTX, arg InsertAppointmentStatusHistoryParams) error
	//InsertConversationSession
	//
	//  INSERT INTO conversation_sessions(
	//      id,
	//      tenant_id,
	//      whatsapp_config_id,
	//      customer_id,
	//      step,
	//      data,
	//      expires_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7
	//  ) ON CONFLICT (tenant_id, customer_id) DO UPDATE
	//      SET step       = EXCLUDED.step,
	//          data       = EXCLUDED.data,
	//          expires_at = EXCLUDED.expires_at,
	//          updated_at = NOW()
	InsertConversationSession(ctx context.Context, db DBTX, arg InsertConversationSessionParams) error
	//InsertCustomer
	//
	//  INSERT INTO customers (id, tenant_id, phone_number)
	//  VALUES ($1, $2, $3)
	//  ON CONFLICT (tenant_id, phone_number) DO NOTHING
	InsertCustomer(ctx context.Context, db DBTX, arg InsertCustomerParams) error
	//InsertOnboardingProgress
	//
	//  INSERT INTO onboarding_progress (id, tenant_id, current_step)
	//  VALUES ($1, $2, $3)
	InsertOnboardingProgress(ctx context.Context, db DBTX, arg InsertOnboardingProgressParams) error
	//InsertResource
	//
	//  INSERT INTO resources(
	//      id,
	//      tenant_id,
	//      name,
	//      type,
	//      avatar_url,
	//      is_active,
	//      sort_order
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      true,
	//      $6
	//  )
	InsertResource(ctx context.Context, db DBTX, arg InsertResourceParams) error
	//InsertResourceService
	//
	//  INSERT INTO resource_services (resource_id, service_id)
	//  VALUES ($1, $2)
	//  ON CONFLICT DO NOTHING
	InsertResourceService(ctx context.Context, db DBTX, arg InsertResourceServiceParams) error
	//InsertScheduleOverride
	//
	//  INSERT INTO schedule_overrides(
	//      id,
	//      resource_id,
	//      date,
	//      is_day_off,
	//      start_time,
	//      end_time,
	//      reason
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7
	//  ) ON CONFLICT (resource_id, date) DO UPDATE
	//      SET is_day_off = EXCLUDED.is_day_off,
	//          start_time = EXCLUDED.start_time,
	//          end_time   = EXCLUDED.end_time,
	//          reason     = EXCLUDED.reason
	InsertScheduleOverride(ctx context.Context, db DBTX, arg InsertScheduleOverrideParams) error
	//InsertService
	//
	//  INSERT INTO services(
	//      id,
	//      tenant_id,
	//      name,
	//      description,
	//      duration_minutes,
	//      buffer_minutes,
	//      price,
	//      is_active,
	//      sort_order
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7,
	//      true,
	//      $8
	//  )
	InsertService(ctx context.Context, db DBTX, arg InsertServiceParams) error
	//InsertTenant
	//
	//  INSERT INTO tenants(
	//      id,
	//      name,
	//      slug,
	//      timezone,
	//      currency,
	//      plan,
	//      appointments_this_month,
	//      month_reset_at,
	//      is_active,
	//      settings
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      0,
	//      $7,
	//      true,
	//      $8
	//  )
	InsertTenant(ctx context.Context, db DBTX, arg InsertTenantParams) error
	//InsertTenantWhatsappConfig
	//
	//  INSERT INTO tenant_whatsapp_configs(
	//      id,
	//      tenant_id,
	//      activation_status,
	//      activation_requested_at,
	//      activation_contact_email,
	//      activation_notes
	//  ) VALUES ($1, $2, 'pending', NOW(), $3, $4)
	//  ON CONFLICT (tenant_id) DO UPDATE
	//      SET activation_status        = 'pending',
	//          activation_requested_at  = NOW(),
	//          activation_contact_email = EXCLUDED.activation_contact_email,
	//          activation_notes         = EXCLUDED.activation_notes
	InsertTenantWhatsappConfig(ctx context.Context, db DBTX, arg InsertTenantWhatsappConfigParams) error
	//LinkTenantUser
	//
	//  INSERT INTO tenant_users (user_id, tenant_id, role)
	//  VALUES ($1, $2, 'admin')
	//  ON CONFLICT (user_id, tenant_id) DO NOTHING
	LinkTenantUser(ctx context.Context, db DBTX, arg LinkTenantUserParams) error
	//Mark24hAppointmentReminderSent
	//
	//  UPDATE appointments
	//  SET reminder_24h_sent_at = COALESCE(reminder_24h_sent_at, $1),
	//      reminder_1h_sent_at  = COALESCE(reminder_1h_sent_at, $2)
	//  WHERE id = $3
	Mark24hAppointmentReminderSent(ctx context.Context, db DBTX, arg Mark24hAppointmentReminderSentParams) error
	//MarkAppointmentReminderEventFailed
	//
	//  UPDATE appointment_reminder_events
	//  SET last_attempt_at = NOW(),
	//      attempts = attempts + 1,
	//      last_error = $2
	//  WHERE id = $1
	//    AND sent_at IS NULL
	MarkAppointmentReminderEventFailed(ctx context.Context, db DBTX, arg MarkAppointmentReminderEventFailedParams) error
	//MarkAppointmentReminderEventSent
	//
	//  UPDATE appointment_reminder_events
	//  SET sent_at = NOW(),
	//      last_attempt_at = NOW(),
	//      attempts = attempts + 1,
	//      last_error = NULL
	//  WHERE id = $1
	//    AND sent_at IS NULL
	MarkAppointmentReminderEventSent(ctx context.Context, db DBTX, id uuid.UUID) error
	//MarkAppointmentReminderSentByType
	//
	//  UPDATE appointments
	//  SET reminder_24h_sent_at = CASE
	//                                 WHEN $1::text = '24h'
	//                                     THEN COALESCE(reminder_24h_sent_at, NOW())
	//                                 ELSE reminder_24h_sent_at
	//      END,
	//      reminder_1h_sent_at  = CASE
	//                                 WHEN $1::text = '1h'
	//                                     THEN COALESCE(reminder_1h_sent_at, NOW())
	//                                 ELSE reminder_1h_sent_at
	//          END
	//  WHERE id = $2::uuid
	//    AND status = 'confirmed'
	MarkAppointmentReminderSentByType(ctx context.Context, db DBTX, arg MarkAppointmentReminderSentByTypeParams) error
	//MarkUnattendedAppointmentsNoShow
	//
	//  UPDATE appointments
	//  SET status = 'no_show',
	//      updated_at = NOW(),
	//      cancelled_by = NULL,
	//      cancel_reason = NULL,
	//      cancelled_at = NULL,
	//      completed_at = NULL
	//  WHERE status = 'confirmed'
	//    AND starts_at <= NOW() - INTERVAL '30 minutes'
	//  RETURNING id, tenant_id, customer_id
	MarkUnattendedAppointmentsNoShow(ctx context.Context, db DBTX) ([]MarkUnattendedAppointmentsNoShowRow, error)
	//SearchAppointments
	//
	//  SELECT a.id,
	//         a.starts_at,
	//         a.ends_at,
	//         a.status,
	//         a.price_at_booking,
	//         r.name                           AS resource_name,
	//         s.name                           AS service_name,
	//         COALESCE(c.name, c.phone_number) AS customer_name
	//  FROM appointments a
	//           JOIN resources r ON r.id = a.resource_id
	//           JOIN services s ON s.id = a.service_id
	//           JOIN customers c ON c.id = a.customer_id
	//  WHERE a.tenant_id = $1
	//    AND a.starts_at >= $2
	//    AND a.starts_at < $3
	//    AND a.resource_id = ANY ($4)
	//    AND a.service_id = ANY ($5)
	//    AND a.status = ANY ($6)
	//  ORDER BY a.starts_at
	SearchAppointments(ctx context.Context, db DBTX, arg SearchAppointmentsParams) ([]SearchAppointmentsRow, error)
	//UnblockCustomer
	//
	//  UPDATE customers
	//  SET is_blocked = false
	//  WHERE id = $1
	//    AND tenant_id = $2
	UnblockCustomer(ctx context.Context, db DBTX, arg UnblockCustomerParams) error
	//UpdateAppointment
	//
	//  UPDATE appointments
	//  SET status        = $1,
	//      updated_at    = NOW(),
	//      cancelled_at  = CASE
	//                          WHEN $1 = 'cancelled'::appointment_status THEN COALESCE(cancelled_at, NOW())
	//                          WHEN status = 'cancelled'::appointment_status THEN NULL
	//                          ELSE cancelled_at
	//          END,
	//      cancelled_by  = $2,
	//      cancel_reason = $3,
	//      completed_at  = $4
	//  WHERE id = $5
	UpdateAppointment(ctx context.Context, db DBTX, arg UpdateAppointmentParams) error
	//UpdateConversationSession
	//
	//  UPDATE conversation_sessions
	//  SET step       = $1,
	//      data       = $2,
	//      expires_at = $3,
	//      updated_at = NOW()
	//  WHERE id = $4
	UpdateConversationSession(ctx context.Context, db DBTX, arg UpdateConversationSessionParams) error
	//UpdateCustomer
	//
	//  UPDATE customers
	//  SET name = $1
	//  WHERE id = $2
	UpdateCustomer(ctx context.Context, db DBTX, arg UpdateCustomerParams) error
	//UpdateResource
	//
	//  UPDATE resources
	//  SET name       = $1,
	//      type       = $2,
	//      avatar_url = $3,
	//      sort_order = $4
	//  WHERE id = $5
	//    AND tenant_id = $6
	UpdateResource(ctx context.Context, db DBTX, arg UpdateResourceParams) error
	//UpdateService
	//
	//  UPDATE services
	//  SET name             = $1,
	//      description      = $2,
	//      duration_minutes = $3,
	//      buffer_minutes   = $4,
	//      price            = $5,
	//      sort_order       = $6
	//  WHERE id = $7
	//    AND tenant_id = $8
	UpdateService(ctx context.Context, db DBTX, arg UpdateServiceParams) error
	//UpdateTenant
	//
	//  UPDATE tenants
	//  SET name       = $1,
	//      timezone   = $2,
	//      settings   = $3,
	//      updated_at = NOW()
	//  WHERE id = $4
	UpdateTenant(ctx context.Context, db DBTX, arg UpdateTenantParams) error
	//UpdateTenantAppointmentCount
	//
	//  UPDATE tenants
	//  SET appointments_this_month = $2,
	//      updated_at              = NOW()
	//  WHERE id = $1
	UpdateTenantAppointmentCount(ctx context.Context, db DBTX, arg UpdateTenantAppointmentCountParams) error
	//UpdateTenantWhatsappConfig
	//
	//  UPDATE tenant_whatsapp_configs
	//  SET access_token     = $1,
	//      token_expires_at = $2,
	//      verified_at      = $3,
	//      updated_at       = NOW()
	//  WHERE id = $4
	UpdateTenantWhatsappConfig(ctx context.Context, db DBTX, arg UpdateTenantWhatsappConfigParams) error
	//UpsertWorkingHours
	//
	//  INSERT INTO working_hours(
	//      id,
	//      resource_id,
	//      day_of_week,
	//      start_time,
	//      end_time,
	//      is_active
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6
	//  ) ON CONFLICT (resource_id, day_of_week) DO UPDATE
	//      SET start_time = EXCLUDED.start_time,
	//          end_time   = EXCLUDED.end_time,
	//          is_active  = EXCLUDED.is_active
	UpsertWorkingHours(ctx context.Context, db DBTX, arg UpsertWorkingHoursParams) error
}

var _ Querier = (*Queries)(nil)
