// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resources_count_by_tenant.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countResourcesByTenant = `-- name: CountResourcesByTenant :one
SELECT tenant_id,
       COUNT(*) AS count
FROM resources
WHERE tenant_id = $1
GROUP BY tenant_id
`

type CountResourcesByTenantRow struct {
	TenantID uuid.UUID `db:"tenant_id"`
	Count    int64     `db:"count"`
}

// CountResourcesByTenant
//
//	SELECT tenant_id,
//	       COUNT(*) AS count
//	FROM resources
//	WHERE tenant_id = $1
//	GROUP BY tenant_id
func (q *Queries) CountResourcesByTenant(ctx context.Context, db DBTX, tenantID uuid.UUID) (CountResourcesByTenantRow, error) {
	row := db.QueryRowContext(ctx, countResourcesByTenant, tenantID)
	var i CountResourcesByTenantRow
	err := row.Scan(&i.TenantID, &i.Count)
	return i, err
}
