// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedule_overrides_find_by_resource.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const findResourceScheduleOverrides = `-- name: FindResourceScheduleOverrides :many
SELECT id,
       resource_id,
       date,
       is_day_off,
       start_time,
       end_time,
       COALESCE(reason, '') as reason,
       created_at
FROM schedule_overrides
WHERE resource_id = $1
  AND date BETWEEN $2 AND $3
ORDER BY date
`

type FindResourceScheduleOverridesParams struct {
	ResourceID uuid.UUID `db:"resource_id"`
	Date       time.Time `db:"date"`
	Date_2     time.Time `db:"date_2"`
}

type FindResourceScheduleOverridesRow struct {
	ID         uuid.UUID      `db:"id"`
	ResourceID uuid.UUID      `db:"resource_id"`
	Date       time.Time      `db:"date"`
	IsDayOff   bool           `db:"is_day_off"`
	StartTime  sql.NullString `db:"start_time"`
	EndTime    sql.NullString `db:"end_time"`
	Reason     string         `db:"reason"`
	CreatedAt  time.Time      `db:"created_at"`
}

// FindResourceScheduleOverrides
//
//	SELECT id,
//	       resource_id,
//	       date,
//	       is_day_off,
//	       start_time,
//	       end_time,
//	       COALESCE(reason, '') as reason,
//	       created_at
//	FROM schedule_overrides
//	WHERE resource_id = $1
//	  AND date BETWEEN $2 AND $3
//	ORDER BY date
func (q *Queries) FindResourceScheduleOverrides(ctx context.Context, db DBTX, arg FindResourceScheduleOverridesParams) ([]FindResourceScheduleOverridesRow, error) {
	rows, err := db.QueryContext(ctx, findResourceScheduleOverrides, arg.ResourceID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindResourceScheduleOverridesRow
	for rows.Next() {
		var i FindResourceScheduleOverridesRow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.Date,
			&i.IsDayOff,
			&i.StartTime,
			&i.EndTime,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
