// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedule_overrides_insert.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const insertScheduleOverride = `-- name: InsertScheduleOverride :exec
INSERT INTO schedule_overrides(
    id,
    resource_id,
    date,
    is_day_off,
    start_time,
    end_time,
    reason
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
) ON CONFLICT (resource_id, date) DO UPDATE
    SET is_day_off = EXCLUDED.is_day_off,
        start_time = EXCLUDED.start_time,
        end_time   = EXCLUDED.end_time,
        reason     = EXCLUDED.reason
`

type InsertScheduleOverrideParams struct {
	ID         uuid.UUID      `db:"id"`
	ResourceID uuid.UUID      `db:"resource_id"`
	Date       time.Time      `db:"date"`
	IsDayOff   bool           `db:"is_day_off"`
	StartTime  sql.NullString `db:"start_time"`
	EndTime    sql.NullString `db:"end_time"`
	Reason     sql.NullString `db:"reason"`
}

// InsertScheduleOverride
//
//	INSERT INTO schedule_overrides(
//	    id,
//	    resource_id,
//	    date,
//	    is_day_off,
//	    start_time,
//	    end_time,
//	    reason
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    $7
//	) ON CONFLICT (resource_id, date) DO UPDATE
//	    SET is_day_off = EXCLUDED.is_day_off,
//	        start_time = EXCLUDED.start_time,
//	        end_time   = EXCLUDED.end_time,
//	        reason     = EXCLUDED.reason
func (q *Queries) InsertScheduleOverride(ctx context.Context, db DBTX, arg InsertScheduleOverrideParams) error {
	_, err := db.ExecContext(ctx, insertScheduleOverride,
		arg.ID,
		arg.ResourceID,
		arg.Date,
		arg.IsDayOff,
		arg.StartTime,
		arg.EndTime,
		arg.Reason,
	)
	return err
}
