// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services_find_by_tenant.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const findServicesByTenantID = `-- name: FindServicesByTenantID :many
SELECT id,
       tenant_id,
       name,
       description,
       duration_minutes,
       buffer_minutes,
       price,
       is_active,
       sort_order,
       created_at
FROM services
WHERE tenant_id = $1
  AND is_active = true
ORDER BY created_at
`

type FindServicesByTenantIDRow struct {
	ID              uuid.UUID      `db:"id"`
	TenantID        uuid.UUID      `db:"tenant_id"`
	Name            string         `db:"name"`
	Description     sql.NullString `db:"description"`
	DurationMinutes int32          `db:"duration_minutes"`
	BufferMinutes   int32          `db:"buffer_minutes"`
	Price           string         `db:"price"`
	IsActive        bool           `db:"is_active"`
	SortOrder       int32          `db:"sort_order"`
	CreatedAt       time.Time      `db:"created_at"`
}

// FindServicesByTenantID
//
//	SELECT id,
//	       tenant_id,
//	       name,
//	       description,
//	       duration_minutes,
//	       buffer_minutes,
//	       price,
//	       is_active,
//	       sort_order,
//	       created_at
//	FROM services
//	WHERE tenant_id = $1
//	  AND is_active = true
//	ORDER BY created_at
func (q *Queries) FindServicesByTenantID(ctx context.Context, db DBTX, tenantID uuid.UUID) ([]FindServicesByTenantIDRow, error) {
	rows, err := db.QueryContext(ctx, findServicesByTenantID, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindServicesByTenantIDRow
	for rows.Next() {
		var i FindServicesByTenantIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.DurationMinutes,
			&i.BufferMinutes,
			&i.Price,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
