// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services_delete.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteService = `-- name: DeleteService :exec
UPDATE services
SET is_active = false
WHERE id = $1
  AND tenant_id = $2
`

type DeleteServiceParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

// DeleteService
//
//	UPDATE services
//	SET is_active = false
//	WHERE id = $1
//	  AND tenant_id = $2
func (q *Queries) DeleteService(ctx context.Context, db DBTX, arg DeleteServiceParams) error {
	_, err := db.ExecContext(ctx, deleteService, arg.ID, arg.TenantID)
	return err
}
