// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services_insert.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const insertService = `-- name: InsertService :exec
INSERT INTO services(
    id,
    tenant_id,
    name,
    description,
    duration_minutes,
    buffer_minutes,
    price,
    is_active,
    sort_order
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    true,
    $8
)
`

type InsertServiceParams struct {
	ID              uuid.UUID      `db:"id"`
	TenantID        uuid.UUID      `db:"tenant_id"`
	Name            string         `db:"name"`
	Description     sql.NullString `db:"description"`
	DurationMinutes int32          `db:"duration_minutes"`
	BufferMinutes   int32          `db:"buffer_minutes"`
	Price           string         `db:"price"`
	SortOrder       int32          `db:"sort_order"`
}

// InsertService
//
//	INSERT INTO services(
//	    id,
//	    tenant_id,
//	    name,
//	    description,
//	    duration_minutes,
//	    buffer_minutes,
//	    price,
//	    is_active,
//	    sort_order
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    $7,
//	    true,
//	    $8
//	)
func (q *Queries) InsertService(ctx context.Context, db DBTX, arg InsertServiceParams) error {
	_, err := db.ExecContext(ctx, insertService,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.DurationMinutes,
		arg.BufferMinutes,
		arg.Price,
		arg.SortOrder,
	)
	return err
}
