// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services_update.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const updateService = `-- name: UpdateService :exec
UPDATE services
SET name             = $1,
    description      = $2,
    duration_minutes = $3,
    buffer_minutes   = $4,
    price            = $5,
    sort_order       = $6
WHERE id = $7
  AND tenant_id = $8
`

type UpdateServiceParams struct {
	Name            string         `db:"name"`
	Description     sql.NullString `db:"description"`
	DurationMinutes int32          `db:"duration_minutes"`
	BufferMinutes   int32          `db:"buffer_minutes"`
	Price           string         `db:"price"`
	SortOrder       int32          `db:"sort_order"`
	ID              uuid.UUID      `db:"id"`
	TenantID        uuid.UUID      `db:"tenant_id"`
}

// UpdateService
//
//	UPDATE services
//	SET name             = $1,
//	    description      = $2,
//	    duration_minutes = $3,
//	    buffer_minutes   = $4,
//	    price            = $5,
//	    sort_order       = $6
//	WHERE id = $7
//	  AND tenant_id = $8
func (q *Queries) UpdateService(ctx context.Context, db DBTX, arg UpdateServiceParams) error {
	_, err := db.ExecContext(ctx, updateService,
		arg.Name,
		arg.Description,
		arg.DurationMinutes,
		arg.BufferMinutes,
		arg.Price,
		arg.SortOrder,
		arg.ID,
		arg.TenantID,
	)
	return err
}
