// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services_find_with_assigned_resource.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const findServicesWithAssignedResourceByTenantID = `-- name: FindServicesWithAssignedResourceByTenantID :many
SELECT DISTINCT s.id,
                s.tenant_id,
                s.name,
                s.description,
                s.duration_minutes,
                s.buffer_minutes,
                s.price,
                s.is_active,
                s.sort_order,
                s.created_at
FROM services s
         JOIN resource_services rs ON rs.service_id = s.id
         JOIN resources r ON r.id = rs.resource_id AND r.is_active = true
WHERE s.tenant_id = $1
  AND s.is_active = true
ORDER BY s.created_at
`

type FindServicesWithAssignedResourceByTenantIDRow struct {
	ID              uuid.UUID      `db:"id"`
	TenantID        uuid.UUID      `db:"tenant_id"`
	Name            string         `db:"name"`
	Description     sql.NullString `db:"description"`
	DurationMinutes int32          `db:"duration_minutes"`
	BufferMinutes   int32          `db:"buffer_minutes"`
	Price           string         `db:"price"`
	IsActive        bool           `db:"is_active"`
	SortOrder       int32          `db:"sort_order"`
	CreatedAt       time.Time      `db:"created_at"`
}

// FindServicesWithAssignedResourceByTenantID
//
//	SELECT DISTINCT s.id,
//	                s.tenant_id,
//	                s.name,
//	                s.description,
//	                s.duration_minutes,
//	                s.buffer_minutes,
//	                s.price,
//	                s.is_active,
//	                s.sort_order,
//	                s.created_at
//	FROM services s
//	         JOIN resource_services rs ON rs.service_id = s.id
//	         JOIN resources r ON r.id = rs.resource_id AND r.is_active = true
//	WHERE s.tenant_id = $1
//	  AND s.is_active = true
//	ORDER BY s.created_at
func (q *Queries) FindServicesWithAssignedResourceByTenantID(ctx context.Context, db DBTX, tenantID uuid.UUID) ([]FindServicesWithAssignedResourceByTenantIDRow, error) {
	rows, err := db.QueryContext(ctx, findServicesWithAssignedResourceByTenantID, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindServicesWithAssignedResourceByTenantIDRow
	for rows.Next() {
		var i FindServicesWithAssignedResourceByTenantIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.DurationMinutes,
			&i.BufferMinutes,
			&i.Price,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
