// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services_find_by_id.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const findServiceByID = `-- name: FindServiceByID :one
SELECT id,
       tenant_id,
       name,
       description,
       duration_minutes,
       buffer_minutes,
       price,
       is_active,
       sort_order,
       created_at
FROM services
WHERE id = $1
  AND is_active = true
`

type FindServiceByIDRow struct {
	ID              uuid.UUID      `db:"id"`
	TenantID        uuid.UUID      `db:"tenant_id"`
	Name            string         `db:"name"`
	Description     sql.NullString `db:"description"`
	DurationMinutes int32          `db:"duration_minutes"`
	BufferMinutes   int32          `db:"buffer_minutes"`
	Price           string         `db:"price"`
	IsActive        bool           `db:"is_active"`
	SortOrder       int32          `db:"sort_order"`
	CreatedAt       time.Time      `db:"created_at"`
}

// FindServiceByID
//
//	SELECT id,
//	       tenant_id,
//	       name,
//	       description,
//	       duration_minutes,
//	       buffer_minutes,
//	       price,
//	       is_active,
//	       sort_order,
//	       created_at
//	FROM services
//	WHERE id = $1
//	  AND is_active = true
func (q *Queries) FindServiceByID(ctx context.Context, db DBTX, id uuid.UUID) (FindServiceByIDRow, error) {
	row := db.QueryRowContext(ctx, findServiceByID, id)
	var i FindServiceByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.DurationMinutes,
		&i.BufferMinutes,
		&i.Price,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}
