// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services_find_by_tenant.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const findServicesByTenantID = `-- name: FindServicesByTenantID :many
SELECT id,
       tenant_id,
       name,
       description,
       duration_minutes,
       buffer_minutes,
       price,
       is_active,
       sort_order,
       created_at
FROM services
WHERE tenant_id = $1
ORDER BY created_at
`

// FindServicesByTenantID
//
//	SELECT id,
//	       tenant_id,
//	       name,
//	       description,
//	       duration_minutes,
//	       buffer_minutes,
//	       price,
//	       is_active,
//	       sort_order,
//	       created_at
//	FROM services
//	WHERE tenant_id = $1
//	ORDER BY created_at
func (q *Queries) FindServicesByTenantID(ctx context.Context, db DBTX, tenantID uuid.UUID) ([]Service, error) {
	rows, err := db.QueryContext(ctx, findServicesByTenantID, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.DurationMinutes,
			&i.BufferMinutes,
			&i.Price,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
