// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant_flow_fields_insert.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const insertTenantFlowField = `-- name: InsertTenantFlowField :exec
INSERT INTO tenant_flow_fields (
    id,
    tenant_id,
    field_key,
    field_type,
    question,
    is_required,
    is_enabled,
    sort_order
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
`

type InsertTenantFlowFieldParams struct {
	ID         uuid.UUID      `db:"id"`
	TenantID   uuid.UUID      `db:"tenant_id"`
	FieldKey   string         `db:"field_key"`
	FieldType  FlowFieldType  `db:"field_type"`
	Question   sql.NullString `db:"question"`
	IsRequired bool           `db:"is_required"`
	IsEnabled  bool           `db:"is_enabled"`
	SortOrder  int32          `db:"sort_order"`
}

// InsertTenantFlowField
//
//	INSERT INTO tenant_flow_fields (
//	    id,
//	    tenant_id,
//	    field_key,
//	    field_type,
//	    question,
//	    is_required,
//	    is_enabled,
//	    sort_order
//	)
//	VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    $7,
//	    $8
//	)
func (q *Queries) InsertTenantFlowField(ctx context.Context, db DBTX, arg InsertTenantFlowFieldParams) error {
	_, err := db.ExecContext(ctx, insertTenantFlowField,
		arg.ID,
		arg.TenantID,
		arg.FieldKey,
		arg.FieldType,
		arg.Question,
		arg.IsRequired,
		arg.IsEnabled,
		arg.SortOrder,
	)
	return err
}
