// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant_whatsapp_configs_find_by_phone_number_id.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const findTenantWhatsappConfigByPhoneNumberID = `-- name: FindTenantWhatsappConfigByPhoneNumberID :one
SELECT twc.id,
       twc.tenant_id,
       twc.waba_id,
       twc.phone_number_id,
       twc.display_phone_number,
       twc.access_token,
       twc.token_expires_at,
       twc.is_active,
       twc.verified_at,
       twc.created_at,
       twc.updated_at,
       t.name      AS tenant_name,
       t.slug      AS tenant_slug,
       t.timezone  AS tenant_timezone,
       t.currency  AS tenant_currency,
       t.settings  AS tenant_settings,
       t.is_active AS tenant_active,
       t.month_reset_at,
       t.appointments_this_month
FROM tenant_whatsapp_configs twc
         JOIN tenants t ON t.id = twc.tenant_id
WHERE twc.phone_number_id = $1
  AND twc.is_active = true
  AND t.is_active = true
LIMIT 1
`

type FindTenantWhatsappConfigByPhoneNumberIDRow struct {
	ID                    uuid.UUID      `db:"id"`
	TenantID              uuid.UUID      `db:"tenant_id"`
	WabaID                sql.NullString `db:"waba_id"`
	PhoneNumberID         sql.NullString `db:"phone_number_id"`
	DisplayPhoneNumber    sql.NullString `db:"display_phone_number"`
	AccessToken           sql.NullString `db:"access_token"`
	TokenExpiresAt        sql.NullTime   `db:"token_expires_at"`
	IsActive              bool           `db:"is_active"`
	VerifiedAt            sql.NullTime   `db:"verified_at"`
	CreatedAt             time.Time      `db:"created_at"`
	UpdatedAt             time.Time      `db:"updated_at"`
	TenantName            string         `db:"tenant_name"`
	TenantSlug            string         `db:"tenant_slug"`
	TenantTimezone        string         `db:"tenant_timezone"`
	TenantCurrency        string         `db:"tenant_currency"`
	TenantSettings        []byte         `db:"tenant_settings"`
	TenantActive          bool           `db:"tenant_active"`
	MonthResetAt          time.Time      `db:"month_reset_at"`
	AppointmentsThisMonth int32          `db:"appointments_this_month"`
}

// FindTenantWhatsappConfigByPhoneNumberID
//
//	SELECT twc.id,
//	       twc.tenant_id,
//	       twc.waba_id,
//	       twc.phone_number_id,
//	       twc.display_phone_number,
//	       twc.access_token,
//	       twc.token_expires_at,
//	       twc.is_active,
//	       twc.verified_at,
//	       twc.created_at,
//	       twc.updated_at,
//	       t.name      AS tenant_name,
//	       t.slug      AS tenant_slug,
//	       t.timezone  AS tenant_timezone,
//	       t.currency  AS tenant_currency,
//	       t.settings  AS tenant_settings,
//	       t.is_active AS tenant_active,
//	       t.month_reset_at,
//	       t.appointments_this_month
//	FROM tenant_whatsapp_configs twc
//	         JOIN tenants t ON t.id = twc.tenant_id
//	WHERE twc.phone_number_id = $1
//	  AND twc.is_active = true
//	  AND t.is_active = true
//	LIMIT 1
func (q *Queries) FindTenantWhatsappConfigByPhoneNumberID(ctx context.Context, db DBTX, phoneNumberID sql.NullString) (FindTenantWhatsappConfigByPhoneNumberIDRow, error) {
	row := db.QueryRowContext(ctx, findTenantWhatsappConfigByPhoneNumberID, phoneNumberID)
	var i FindTenantWhatsappConfigByPhoneNumberIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WabaID,
		&i.PhoneNumberID,
		&i.DisplayPhoneNumber,
		&i.AccessToken,
		&i.TokenExpiresAt,
		&i.IsActive,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantName,
		&i.TenantSlug,
		&i.TenantTimezone,
		&i.TenantCurrency,
		&i.TenantSettings,
		&i.TenantActive,
		&i.MonthResetAt,
		&i.AppointmentsThisMonth,
	)
	return i, err
}
