// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants_reject_pending_activation.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const rejectTenantActivation = `-- name: RejectTenantActivation :exec
UPDATE tenant_whatsapp_configs
SET reject_reason     = $1,
    activation_status = 'failed',
    updated_at        = NOW()
WHERE tenant_id = $2
`

type RejectTenantActivationParams struct {
	RejectReason sql.NullString `db:"reject_reason"`
	TenantID     uuid.UUID      `db:"tenant_id"`
}

// RejectTenantActivation
//
//	UPDATE tenant_whatsapp_configs
//	SET reject_reason     = $1,
//	    activation_status = 'failed',
//	    updated_at        = NOW()
//	WHERE tenant_id = $2
func (q *Queries) RejectTenantActivation(ctx context.Context, db DBTX, arg RejectTenantActivationParams) error {
	_, err := db.ExecContext(ctx, rejectTenantActivation, arg.RejectReason, arg.TenantID)
	return err
}
