// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant_flow_fields_update.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const updateFlowField = `-- name: UpdateFlowField :exec
UPDATE tenant_flow_fields
SET question    = $3,
    is_required = $4,
    sort_order  = $5
WHERE id = $1
  AND tenant_id = $2
`

type UpdateFlowFieldParams struct {
	ID         uuid.UUID      `db:"id"`
	TenantID   uuid.UUID      `db:"tenant_id"`
	Question   sql.NullString `db:"question"`
	IsRequired bool           `db:"is_required"`
	SortOrder  int32          `db:"sort_order"`
}

// UpdateFlowField
//
//	UPDATE tenant_flow_fields
//	SET question    = $3,
//	    is_required = $4,
//	    sort_order  = $5
//	WHERE id = $1
//	  AND tenant_id = $2
func (q *Queries) UpdateFlowField(ctx context.Context, db DBTX, arg UpdateFlowFieldParams) error {
	_, err := db.ExecContext(ctx, updateFlowField,
		arg.ID,
		arg.TenantID,
		arg.Question,
		arg.IsRequired,
		arg.SortOrder,
	)
	return err
}
