// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants_insert.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertTenant = `-- name: InsertTenant :exec
INSERT INTO tenants(
    id,
    name,
    slug,
    timezone,
    currency,
    plan,
    appointments_this_month,
    month_reset_at,
    is_active,
    settings
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    0,
    $7,
    true,
    $8
)
`

type InsertTenantParams struct {
	ID           uuid.UUID `db:"id"`
	Name         string    `db:"name"`
	Slug         string    `db:"slug"`
	Timezone     string    `db:"timezone"`
	Currency     string    `db:"currency"`
	Plan         string    `db:"plan"`
	MonthResetAt time.Time `db:"month_reset_at"`
	Settings     []byte    `db:"settings"`
}

// InsertTenant
//
//	INSERT INTO tenants(
//	    id,
//	    name,
//	    slug,
//	    timezone,
//	    currency,
//	    plan,
//	    appointments_this_month,
//	    month_reset_at,
//	    is_active,
//	    settings
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    0,
//	    $7,
//	    true,
//	    $8
//	)
func (q *Queries) InsertTenant(ctx context.Context, db DBTX, arg InsertTenantParams) error {
	_, err := db.ExecContext(ctx, insertTenant,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Timezone,
		arg.Currency,
		arg.Plan,
		arg.MonthResetAt,
		arg.Settings,
	)
	return err
}
