// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants_find_by_id.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findTenantByID = `-- name: FindTenantByID :one
SELECT id,
       name,
       slug,
       timezone,
       currency,
       appointments_this_month,
       month_reset_at,
       is_active,
       settings,
       created_at,
       updated_at
FROM tenants
WHERE id = $1
  AND is_active = true
LIMIT 1
`

type FindTenantByIDRow struct {
	ID                    uuid.UUID `db:"id"`
	Name                  string    `db:"name"`
	Slug                  string    `db:"slug"`
	Timezone              string    `db:"timezone"`
	Currency              string    `db:"currency"`
	AppointmentsThisMonth int32     `db:"appointments_this_month"`
	MonthResetAt          time.Time `db:"month_reset_at"`
	IsActive              bool      `db:"is_active"`
	Settings              []byte    `db:"settings"`
	CreatedAt             time.Time `db:"created_at"`
	UpdatedAt             time.Time `db:"updated_at"`
}

// FindTenantByID
//
//	SELECT id,
//	       name,
//	       slug,
//	       timezone,
//	       currency,
//	       appointments_this_month,
//	       month_reset_at,
//	       is_active,
//	       settings,
//	       created_at,
//	       updated_at
//	FROM tenants
//	WHERE id = $1
//	  AND is_active = true
//	LIMIT 1
func (q *Queries) FindTenantByID(ctx context.Context, db DBTX, id uuid.UUID) (FindTenantByIDRow, error) {
	row := db.QueryRowContext(ctx, findTenantByID, id)
	var i FindTenantByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Timezone,
		&i.Currency,
		&i.AppointmentsThisMonth,
		&i.MonthResetAt,
		&i.IsActive,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
