// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants_find_active_plan.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const findActivePlanByTenant = `-- name: FindActivePlanByTenant :one
SELECT p.id,
       p.external_id,
       p.environment,
       p.features
FROM subscriptions ts
         JOIN plans p ON p.id = ts.plan_id
WHERE ts.tenant_id = $1
  AND ts.status IN ('active', 'trialing')
  AND ts.environment = $2
LIMIT 1
`

type FindActivePlanByTenantParams struct {
	TenantID    uuid.UUID `db:"tenant_id"`
	Environment string    `db:"environment"`
}

type FindActivePlanByTenantRow struct {
	ID          uuid.UUID       `db:"id"`
	ExternalID  string          `db:"external_id"`
	Environment string          `db:"environment"`
	Features    json.RawMessage `db:"features"`
}

// FindActivePlanByTenant
//
//	SELECT p.id,
//	       p.external_id,
//	       p.environment,
//	       p.features
//	FROM subscriptions ts
//	         JOIN plans p ON p.id = ts.plan_id
//	WHERE ts.tenant_id = $1
//	  AND ts.status IN ('active', 'trialing')
//	  AND ts.environment = $2
//	LIMIT 1
func (q *Queries) FindActivePlanByTenant(ctx context.Context, db DBTX, arg FindActivePlanByTenantParams) (FindActivePlanByTenantRow, error) {
	row := db.QueryRowContext(ctx, findActivePlanByTenant, arg.TenantID, arg.Environment)
	var i FindActivePlanByTenantRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Environment,
		&i.Features,
	)
	return i, err
}
