// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant_flow_fields_create_predefined_fields.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createTenantPredefinedFlowFields = `-- name: CreateTenantPredefinedFlowFields :exec
WITH fields AS (
    SELECT
        $2::text[] AS field_keys,
        $3::int[] AS sort_orders
)
INSERT INTO tenant_flow_fields (
    id,
    tenant_id,
    field_key,
    field_type,
    question,
    is_required,
    is_enabled,
    sort_order
)
SELECT
    gen_random_uuid(),
    $1,
    UNNEST(fields.field_keys),
    'predefined',
    NULL,
    false,
    false,
    UNNEST(fields.sort_orders)
FROM fields
ON CONFLICT (tenant_id, field_key) DO NOTHING
`

type CreateTenantPredefinedFlowFieldsParams struct {
	TenantID   uuid.UUID `db:"tenant_id"`
	FieldKeys  []string  `db:"field_keys"`
	SortOrders []int32   `db:"sort_orders"`
}

// CreateTenantPredefinedFlowFields
//
//	WITH fields AS (
//	    SELECT
//	        $2::text[] AS field_keys,
//	        $3::int[] AS sort_orders
//	)
//	INSERT INTO tenant_flow_fields (
//	    id,
//	    tenant_id,
//	    field_key,
//	    field_type,
//	    question,
//	    is_required,
//	    is_enabled,
//	    sort_order
//	)
//	SELECT
//	    gen_random_uuid(),
//	    $1,
//	    UNNEST(fields.field_keys),
//	    'predefined',
//	    NULL,
//	    false,
//	    false,
//	    UNNEST(fields.sort_orders)
//	FROM fields
//	ON CONFLICT (tenant_id, field_key) DO NOTHING
func (q *Queries) CreateTenantPredefinedFlowFields(ctx context.Context, db DBTX, arg CreateTenantPredefinedFlowFieldsParams) error {
	_, err := db.ExecContext(ctx, createTenantPredefinedFlowFields, arg.TenantID, pq.Array(arg.FieldKeys), pq.Array(arg.SortOrders))
	return err
}
