// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant_whatsapp_configs_find_by_tenant.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const findTenantWhatsappConfig = `-- name: FindTenantWhatsappConfig :one
SELECT id,
       tenant_id,
       waba_id,
       phone_number_id,
       display_phone_number,
       access_token,
       token_expires_at,
       is_active,
       activation_contact_email,
       verified_at,
       created_at,
       updated_at
FROM tenant_whatsapp_configs
WHERE tenant_id = $1
  AND is_active = true
LIMIT 1
`

type FindTenantWhatsappConfigRow struct {
	ID                     uuid.UUID      `db:"id"`
	TenantID               uuid.UUID      `db:"tenant_id"`
	WabaID                 sql.NullString `db:"waba_id"`
	PhoneNumberID          sql.NullString `db:"phone_number_id"`
	DisplayPhoneNumber     sql.NullString `db:"display_phone_number"`
	AccessToken            sql.NullString `db:"access_token"`
	TokenExpiresAt         sql.NullTime   `db:"token_expires_at"`
	IsActive               bool           `db:"is_active"`
	ActivationContactEmail sql.NullString `db:"activation_contact_email"`
	VerifiedAt             sql.NullTime   `db:"verified_at"`
	CreatedAt              time.Time      `db:"created_at"`
	UpdatedAt              time.Time      `db:"updated_at"`
}

// FindTenantWhatsappConfig
//
//	SELECT id,
//	       tenant_id,
//	       waba_id,
//	       phone_number_id,
//	       display_phone_number,
//	       access_token,
//	       token_expires_at,
//	       is_active,
//	       activation_contact_email,
//	       verified_at,
//	       created_at,
//	       updated_at
//	FROM tenant_whatsapp_configs
//	WHERE tenant_id = $1
//	  AND is_active = true
//	LIMIT 1
func (q *Queries) FindTenantWhatsappConfig(ctx context.Context, db DBTX, tenantID uuid.UUID) (FindTenantWhatsappConfigRow, error) {
	row := db.QueryRowContext(ctx, findTenantWhatsappConfig, tenantID)
	var i FindTenantWhatsappConfigRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WabaID,
		&i.PhoneNumberID,
		&i.DisplayPhoneNumber,
		&i.AccessToken,
		&i.TokenExpiresAt,
		&i.IsActive,
		&i.ActivationContactEmail,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
