// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants_find_by_user_id.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findTenantByUserId = `-- name: FindTenantByUserId :one
SELECT t.id,
       t.name,
       t.slug,
       t.timezone,
       t.currency,
       t.appointments_this_month,
       t.month_reset_at,
       t.is_active,
       t.settings,
       t.created_at,
       t.updated_at
FROM tenants t
         JOIN tenant_users tu ON tu.tenant_id = t.id
WHERE tu.user_id = $1
  AND t.is_active = true
LIMIT 1
`

type FindTenantByUserIdRow struct {
	ID                    uuid.UUID `db:"id"`
	Name                  string    `db:"name"`
	Slug                  string    `db:"slug"`
	Timezone              string    `db:"timezone"`
	Currency              string    `db:"currency"`
	AppointmentsThisMonth int32     `db:"appointments_this_month"`
	MonthResetAt          time.Time `db:"month_reset_at"`
	IsActive              bool      `db:"is_active"`
	Settings              []byte    `db:"settings"`
	CreatedAt             time.Time `db:"created_at"`
	UpdatedAt             time.Time `db:"updated_at"`
}

// FindTenantByUserId
//
//	SELECT t.id,
//	       t.name,
//	       t.slug,
//	       t.timezone,
//	       t.currency,
//	       t.appointments_this_month,
//	       t.month_reset_at,
//	       t.is_active,
//	       t.settings,
//	       t.created_at,
//	       t.updated_at
//	FROM tenants t
//	         JOIN tenant_users tu ON tu.tenant_id = t.id
//	WHERE tu.user_id = $1
//	  AND t.is_active = true
//	LIMIT 1
func (q *Queries) FindTenantByUserId(ctx context.Context, db DBTX, userID string) (FindTenantByUserIdRow, error) {
	row := db.QueryRowContext(ctx, findTenantByUserId, userID)
	var i FindTenantByUserIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Timezone,
		&i.Currency,
		&i.AppointmentsThisMonth,
		&i.MonthResetAt,
		&i.IsActive,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
