// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants_update.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const updateTenant = `-- name: UpdateTenant :exec
UPDATE tenants
SET name       = $1,
    timezone   = $2,
    settings   = $3,
    updated_at = NOW()
WHERE id = $4
`

type UpdateTenantParams struct {
	Name     string    `db:"name"`
	Timezone string    `db:"timezone"`
	Settings []byte    `db:"settings"`
	ID       uuid.UUID `db:"id"`
}

// UpdateTenant
//
//	UPDATE tenants
//	SET name       = $1,
//	    timezone   = $2,
//	    settings   = $3,
//	    updated_at = NOW()
//	WHERE id = $4
func (q *Queries) UpdateTenant(ctx context.Context, db DBTX, arg UpdateTenantParams) error {
	_, err := db.ExecContext(ctx, updateTenant,
		arg.Name,
		arg.Timezone,
		arg.Settings,
		arg.ID,
	)
	return err
}
