// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant_flow_fields_toggle.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const toggleFlowField = `-- name: ToggleFlowField :exec
UPDATE tenant_flow_fields
SET is_enabled = NOT is_enabled
WHERE id = $1
  AND tenant_id = $2
`

type ToggleFlowFieldParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

// ToggleFlowField
//
//	UPDATE tenant_flow_fields
//	SET is_enabled = NOT is_enabled
//	WHERE id = $1
//	  AND tenant_id = $2
func (q *Queries) ToggleFlowField(ctx context.Context, db DBTX, arg ToggleFlowFieldParams) error {
	_, err := db.ExecContext(ctx, toggleFlowField, arg.ID, arg.TenantID)
	return err
}
