// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users_find_by_id.sql

package db

import (
	"context"
	"database/sql"
)

const findUserByID = `-- name: FindUserByID :one
SELECT id, banned, ban_reason, ban_expires
FROM users
WHERE id = $1
LIMIT 1
`

type FindUserByIDRow struct {
	ID         string         `db:"id"`
	Banned     sql.NullBool   `db:"banned"`
	BanReason  sql.NullString `db:"ban_reason"`
	BanExpires sql.NullTime   `db:"ban_expires"`
}

// FindUserByID
//
//	SELECT id, banned, ban_reason, ban_expires
//	FROM users
//	WHERE id = $1
//	LIMIT 1
func (q *Queries) FindUserByID(ctx context.Context, db DBTX, id string) (FindUserByIDRow, error) {
	row := db.QueryRowContext(ctx, findUserByID, id)
	var i FindUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Banned,
		&i.BanReason,
		&i.BanExpires,
	)
	return i, err
}
