version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: wappiz
    main: ./cmd/api
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: wappiz

    ldflags:
      - -s -w
      - -X 'wappiz/pkg/buildinfo.Version={{.Version}}'
      - -X 'wappiz/pkg/buildinfo.Revision={{.FullCommit}}'
      - -X 'wappiz/pkg/buildinfo.BuildTime={{.Date}}'

upx:
  - enabled: true
    ids:
      - wappiz
    goos:
      - linux # UPX doesn't support macOS
    compress: best
    lzma: true

archives:
  - id: wappiz
    formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  prerelease: auto
