load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "appointments_reschedule",
    srcs = ["handler.go"],
    importpath = "wappiz/svc/api/routes/v1/appointments_reschedule",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/events",
        "//internal/services/slotfinder",
        "//pkg/codes",
        "//pkg/db",
        "//pkg/fault",
        "//pkg/server",
        "//svc/api/internal/middleware",
        "@com_github_gin_gonic_gin//:gin",
        "@com_github_google_uuid//:uuid",
        "@com_github_jackc_pgx_v5//pgconn",
    ],
)
