load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "jwt",
    srcs = [
        "errors.go",
        "interface.go",
        "jwt.go",
        "verifier.go",
    ],
    importpath = "wappiz/pkg/jwt",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/db",
        "@com_github_golang_jwt_jwt_v5//:jwt",
        "@org_golang_x_sync//singleflight",
    ],
)

go_test(
    name = "jwt_test",
    srcs = ["verifier_test.go"],
    embed = [":jwt"],
    deps = [
        "@com_github_golang_jwt_jwt_v5//:jwt",
        "@com_github_stretchr_testify//require",
    ],
)
