load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "customers_list",
    srcs = ["handler.go"],
    importpath = "wappiz/svc/api/routes/v1/customers_list",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/db",
        "//pkg/fault",
        "//svc/api/internal/middleware",
        "@com_github_gin_gonic_gin//:gin",
        "@com_github_google_uuid//:uuid",
    ],
)
