load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "middleware",
    srcs = [
        "authentication.go",
        "errors.go",
        "webhook_signature.go",
    ],
    importpath = "wappiz/svc/api/internal/middleware",
    visibility = ["//svc/api:__subpackages__"],
    deps = [
        "//pkg/codes",
        "//pkg/db",
        "//pkg/fault",
        "//pkg/jwt",
        "//pkg/logger",
        "//svc/api/openapi",
        "@com_github_gin_gonic_gin//:gin",
        "@com_github_google_uuid//:uuid",
    ],
)

go_test(
    name = "middleware_test",
    srcs = ["authentication_test.go"],
    embed = [":middleware"],
    deps = [
        "//pkg/db",
        "@com_github_stretchr_testify//require",
    ],
)
